### ISSUE TITLE
Incorrect version string

### ISSUE THREAD

**Issue by glowkeeper** [minima-global/Minima#14]
In Setting/Apps/Minima/Advanced, the version string says "0.96.36", which I _think_ might be a bit out of date.

**Comment by eurobuddha** [comment]
Setting/Apps/Minima/Advaced

now says 97.5 when im running 97.7

we need to keep this up to date.

close?

**Comment by glowkeeper** [comment]
What does it say when you go into Settings/App on Android?

**Comment by glowkeeper** [comment]
Mine says 97.5, too - @spartacusrex99 - version string update, please :)

**Comment by eurobuddha** [comment]
fixed  in 0.97.12
