### ISSUE TITLE
Coinmaster coins not spendable

### ISSUE THREAD

**Issue by eurobuddha** [minima-global/Minima#232]
I was attempting to aggregate all my coins into one large UTXO I had 250 odd utxo and 12000 coins, i merged most  of them but 12 hours later ony 4k are spendable and the rest are trapped in the netherworld.

![image](https://user-images.githubusercontent.com/36900242/119454790-d4ba6f80-bd30-11eb-9458-991981d3237c.png)
 please advise

I flushed mempool but that didnt help.

logs here

[coinblaster.docx](https://github.com/minima-global/Minima/files/6537234/coinblaster.docx)

**Comment by eliasnemr** [comment]
This is not a new bug, it seems as if coins are unable to be spent after
you try to stuff them all in a txpow and they get rejected due to the fact
the transaction is too big for all the signatures then they become
unspendable.  Think Paddy had a look at that & fixed it?

**Comment by eurobuddha** [comment]
ok glad to have broken here again.
my position still remains all this aggregation should be automatic as needed from wallet request.
Coinmaster should be more for splitting larger UTxOs

**Comment by eurobuddha** [comment]
fixed in 98.26
