### ISSUE TITLE
Moving Larger amounts of Minima

### ISSUE THREAD

**Issue by eurobuddha** [minima-global/Minima#234]
Currently it is impossible to send large amounts of Minima, anything over a few hundred needs to laboriously coin mastered and there are limits to and annoyances there.
From the wallet 200-250 is the maximum possible without an error message. once in coin master you are presented with lists of 25 minima utxos which cannot be aggregated more than 4-6 at a time. Laborious and time consuming.
I have tried to move 15000 minima from one wallet to another and thought that power console iterating 100 minima clips would solev the issues, but power console does not work with a simple command like 

send 100 Mx3RUCXVKCNXFI37FO6CQYAK5G24ULEJ3W 0x00

i attempted to use sendpoll, but was unsure on how it worked i used

sendpoll 10000 Mx3RUCXVKCNXFI37FO6CQYAK5G24ULEJ3W 0x00
sendpoll 100_100_ Mx3RUCXVKCNXFI37FO6CQYAK5G24ULEJ3W 0x00

now I have 10000 minima missing from my wallet but not in the destination wallet

This situation of not being able to send larger amounts is a BIG issue and I am marking this issue as critical.

i am attempting to attach the logs here...

**Comment by eurobuddha** [comment]
[sendpoll.txt](https://github.com/minima-global/Minima/files/6566279/sendpoll.txt)

**Comment by eurobuddha** [comment]
what will Minima whales do?

this is mission critical and needs an elegant effortless solution, one where the user doesn't have to do a thing

**Comment by eurobuddha** [comment]
![image](https://user-images.githubusercontent.com/36900242/120106591-8ef90f00-c155-11eb-9ca5-7bcf1b8be008.png)

![image](https://user-images.githubusercontent.com/36900242/120106607-a637fc80-c155-11eb-9221-4d5f3d91243d.png)

**Comment by eurobuddha** [comment]
in addition when using the send 100 Mx3RUCXVKCNXFI37FO6CQYAK5G24ULEJ3W 0x00 command in terminal i received timed out and false but transaction went through

**Comment by eurobuddha** [comment]
![image](https://user-images.githubusercontent.com/36900242/120106655-e0090300-c155-11eb-993b-f20c8b2e3d2d.png)

returns nothing and fails

**Comment by eurobuddha** [comment]
![image](https://user-images.githubusercontent.com/36900242/120106696-07f86680-c156-11eb-98f0-521ac0c1c453.png)

accepted but outsized amount cannot be sent

**Comment by eurobuddha** [comment]
![image](https://user-images.githubusercontent.com/36900242/120106838-8ead4380-c156-11eb-8008-0c0f0760fbba.png)

**Comment by eurobuddha** [comment]
[sendpoll_recreated.txt](https://github.com/minima-global/Minima/files/6566299/sendpoll_recreated.txt)
  

ok so after a few timed out messaged I get 10-15 pages  the logs above show the beginning and the end, for some reason on tmux i cant save it all in one go.

**Comment by eurobuddha** [comment]
on so on this node now I have 13000 missing coins sent to 

Mx3RUCXVKCNXFI37FO6CQYAK5G24ULEJ3W

....

**Comment by eurobuddha** [comment]
I'm sure I'm using sendpoll wrong , but the critical bug is the impossibility to transfer large size

**Comment by glowkeeper** [comment]
You were using the wroing version of _`Power Console` - I've just used it to send 60 lots of 10000 from one address to another, and it works just fine. Please confirm.

**Comment by eurobuddha** [comment]
solved in 98.26
