### ISSUE TITLE
Time out after gimmi use 

### ISSUE THREAD

**Issue by BoldorXL** [minima-global/Minima#240]
Hello Support, 

After using the gimmi button I got a time out window. What ive noticed is during using the wallet it's slightly slowing down when using the gimmi. Also I had 1 time that the spinning wheel was not showing. 
Further more, I have been testing the deleting and reinstalling Minima using the backup option, works great. But if I go over my history I'm not seeing all gimmi actions, is this normal ?

Al this on my Samsung galaxy S20+ G5
![Screenshot_20210604-123355_Brave](https://user-images.githubusercontent.com/73369734/120796180-cba07e00-c53a-11eb-8412-748a86c4e888.jpg)

Grz. Bob 
Aka BoldorXL

**Comment by eurobuddha** [comment]
Could you please supply the logs frowhen this happened, or reproduce and send the logs from them sir
