### ISSUE TITLE
Balance and History not matching 

### ISSUE THREAD

**Issue by BoldorXL** [minima-global/Minima#241]
Issue Impact: Minor Issue 

Device Manufacturer: Samsung
Device Model: Galaxi S20+ 5G
Divice OS: Android 
Device OS Version: 11
Application Version: 3.1
What Happend?
What Did You Expect To Happen: History and Balance would be the same.
Can't reproduce it. Closing and Restarting 
and it's still the same.
More info in the video

Cheers,

BoldorXL 

https://user-images.githubusercontent.com/73369734/120811153-f7782f80-c54b-11eb-83c7-d4c9bf9c61cc.mp4

**Comment by eliasnemr** [comment]
Hi Boldor,

I’ve just seen your video, it looks like it may be in your mempool still as
it’s flashing.

Elias

**Comment by BoldorXL** [comment]
I think it something els bc it's still not correct and flashing ever since

**Comment by BoldorXL** [comment]
I hope the log file will be uploaded now

**Comment by BoldorXL** [comment]
Can someone tell me how to attach a file to a reply. I can select a file but it not showing

**Comment by eurobuddha** [comment]
check the mempool too please

**Comment by eurobuddha** [comment]
coin stuck in mempool, should be solved in 98.24

**Comment by BoldorXL** [comment]
Cleared the mempool was the solution to solve the problem using flushmempool -hard. At first I didn't see any changes. I had to close the window en op the wallet again to see all was fine. I wonder if it is possible to see the outcome of such actions right away without closing and Re-starting the wallet. Is this programmable? 
After some more reading I've seen the help text also mentioned the solution. But I think that it would be more user friendly if there is some kind of trouble shooting menu that is easy excusable and user friendly.... just a thought. But of course it's testing time so if all goes well it's something of the past already 🙂

**Comment by eliasnemr** [comment]
Once the coins hit the mempool the transaction is registered by History and not after.  If the transaction is invalid and doesn't go through so the balance doesn't change.  This is currently being worked on an is going to be fixed in the next hard fork of the apk.

**Comment by Sw1fty** [comment]
@eliasnemr was this fixed?
