### ISSUE TITLE
Enhancement: Wallet > Send > Transaction Confirmation: Ability to see Public Message

### ISSUE THREAD

**Issue by jazminrib** [minima-global/Minima#242]
Issue Impact: Minor
Device Manufacturer: Samsung
Device Model: S10
Device OS: Android
Device OS Version: 11
Application Version: apk: v0.98.20 wallet version 1.1.2
What Happened?: On the send transaction confirmation screen, all details are shown except the public message
What Did You Expect To Happen? Would like to see the public message as well
Steps to Recreate Issue: Send a transaction
![TXConf](https://user-images.githubusercontent.com/60537663/120815303-964e5d00-c547-11eb-9339-ff1d6d4402ae.jpg)

**Comment by eurobuddha** [comment]
good idea

**Comment by eliasnemr** [comment]
Now implemented in v1.1.4

**Comment by jazminrib** [comment]
Tested and confirm the public message is viewable when confirming a transaction. Thanks

**Comment by eurobuddha** [comment]
closing
