### ISSUE TITLE
Wallet > History Updated before TX is confirmed

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#243]
Issue Impact: Minor
Device Manufacturer: Samsung
Device Model: S10
Device OS: Android
Device OS Version: 11
Application Version: apk: v0.98.20 wallet version 1.1.2
What Happened?: After clicking Gimme50, the History is updated immediately with a status of "Completed" but the tx is still either in the mempool or unconfirmed. 

What Did You Expect To Happen? The tx would not show in the History as Completed until it is confirmed.
Steps to Recreate Issue: Hit Gimme 50 > Check History > Balance: see the tx is still not confirmed

Screenshot1: Time 12:25, transaction shows as completed in History
Screenshot2: Time 12:26, transaction still unconfirmed in Balance

![HistoryUpdated](https://user-images.githubusercontent.com/60537663/120819129-293cc680-c54b-11eb-90d5-9654ae037cda.jpg)

![TXNotFinished](https://user-images.githubusercontent.com/60537663/120819172-35c11f00-c54b-11eb-9f38-a1e9ec953407.jpg)

Logs: 

Minima @ 04/06/2021 12:14:22 [84.2 MB] : CONNECTED TO SERVICE
Minima @ 04/06/2021 12:14:22 [84.2 MB] : ACTIVITY : INITIAL SYNC COMPLETE ON STARTUP..
Minima @ 04/06/2021 12:14:22 [84.3 MB] : ACTIVITY : GET STARTED
Minima @ 04/06/2021 12:14:49 [102.8 MB] : NEW base address created [7 / 14] : Mx2RXFKNEDIYZGTPW3AOBEMWHJXQCBOOBK
Minima @ 04/06/2021 12:14:54 [77.7 MB] : NEW base address created [24 / 15] : MxSMWNONLS64HUPR3F4CPQX5KCFDWREB53
Minima @ 04/06/2021 12:14:54 [78.9 MB] : START TXPOW MINING @ 126918 {"inputs":[{"coinid":"0xFEED50FEED50FEED50FEED50","address":"0x1F5215419EE7D3A2D2EAF4235E68F5072B0242E5","mxaddress":"MxD5JBKQM647J2FUXK6QRV42HVA4VQEQXF","amount":"50","tokenid":"0x00","floating":false,"storestate":true}],"outputs":[{"coinid":"0x00","address":"0xD46E553483463269BEDB03824658E9BC0417382A","mxaddress":"Mx2RXFKNEDIYZGTPW3AOBEMWHJXQCBOOBK","amount":"25","tokenid":"0x00","floating":false,"storestate":true},{"coinid":"0x00","address":"0x932CD73572F70F47C765E09F0BF54228ED1207BB","mxaddress":"MxSMWNONLS64HUPR3F4CPQX5KCFDWREB53","amount":"25","tokenid":"0x00","floating":false,"storestate":true}],"state":[],"linkhash":"0x00"}
Minima @ 04/06/2021 12:14:59 [118.0 MB] : NOTFINISHED 41191
Minima @ 04/06/2021 12:14:59 [118.6 MB] : START TXPOW MINING @ 126919 {"inputs":[{"coinid":"0xFEED50FEED50FEED50FEED50","address":"0x1F5215419EE7D3A2D2EAF4235E68F5072B0242E5","mxaddress":"MxD5JBKQM647J2FUXK6QRV42HVA4VQEQXF","amount":"50","tokenid":"0x00","floating":false,"storestate":true}],"outputs":[{"coinid":"0x00","address":"0xD46E553483463269BEDB03824658E9BC0417382A","mxaddress":"Mx2RXFKNEDIYZGTPW3AOBEMWHJXQCBOOBK","amount":"25","tokenid":"0x00","floating":false,"storestate":true},{"coinid":"0x00","address":"0x932CD73572F70F47C765E09F0BF54228ED1207BB","mxaddress":"MxSMWNONLS64HUPR3F4CPQX5KCFDWREB53","amount":"25","tokenid":"0x00","floating":false,"storestate":true}],"state":[],"linkhash":"0x00"}
Minima @ 04/06/2021 12:15:04 [115.4 MB] : NOTFINISHED 40665
Minima @ 04/06/2021 12:15:04 [115.9 MB] : START TXPOW MINING @ 126919 {"inputs":[{"coinid":"0xFEED50FEED50FEED50FEED50","address":"0x1F5215419EE7D3A2D2EAF4235E68F5072B0242E5","mxaddress":"MxD5JBKQM647J2FUXK6QRV42HVA4VQEQXF","amount":"50","tokenid":"0x00","floating":false,"storestate":true}],"outputs":[{"coinid":"0x00","address":"0xD46E553483463269BEDB03824658E9BC0417382A","mxaddress":"Mx2RXFKNEDIYZGTPW3AOBEMWHJXQCBOOBK","amount":"25","tokenid":"0x00","floating":false,"storestate":true},{"coinid":"0x00","address":"0x932CD73572F70F47C765E09F0BF54228ED1207BB","mxaddress":"MxSMWNONLS64HUPR3F4CPQX5KCFDWREB53","amount":"25","tokenid":"0x00","floating":false,"storestate":true}],"state":[],"linkhash":"0x00"}
Minima @ 04/06/2021 12:15:09 [105.1 MB] : NOTFINISHED 41218
Minima @ 04/06/2021 12:15:09 [105.6 MB] : START TXPOW MINING @ 126919 {"inputs":[{"coinid":"0xFEED50FEED50FEED50FEED50","address":"0x1F5215419EE7D3A2D2EAF4235E68F5072B0242E5","mxaddress":"MxD5JBKQM647J2FUXK6QRV42HVA4VQEQXF","amount":"50","tokenid":"0x00","floating":false,"storestate":true}],"outputs":[{"coinid":"0x00","address":"0xD46E553483463269BEDB03824658E9BC0417382A","mxaddress":"Mx2RXFKNEDIYZGTPW3AOBEMWHJXQCBOOBK","amount":"25","tokenid":"0x00","floating":false,"storestate":true},{"coinid":"0x00","address":"0x932CD73572F70F47C765E09F0BF54228ED1207BB","mxaddress":"MxSMWNONLS64HUPR3F4CPQX5KCFDWREB53","amount":"25","tokenid":"0x00","floating":false,"storestate":true}],"state":[],"linkhash":"0x00"}
Minima @ 04/06/2021 12:15:14 [102.3 MB] : NOTFINISHED 41376
Minima @ 04/06/2021 12:15:14 [102.8 MB] : START TXPOW MINING @ 126919 {"inputs":[{"coinid":"0xFEED50FEED50FEED50FEED50","address":"0x1F5215419EE7D3A2D2EAF4235E68F5072B0242E5","mxaddress":"MxD5JBKQM647J2FUXK6QRV42HVA4VQEQXF","amount":"50","tokenid":"0x00","floating":false,"storestate":true}],"outputs":[{"coinid":"0x00","address":"0xD46E553483463269BEDB03824658E9BC0417382A","mxaddress":"Mx2RXFKNEDIYZGTPW3AOBEMWHJXQCBOOBK","amount":"25","tokenid":"0x00","floating":false,"storestate":true},{"coinid":"0x00","address":"0x932CD73572F70F47C765E09F0BF54228ED1207BB","mxaddress":"MxSMWNONLS64HUPR3F4CPQX5KCFDWREB53","amount":"25","tokenid":"0x00","floating":false,"storestate":true}],"state":[],"linkhash":"0x00"}
Minima @ 04/06/2021 12:15:19 [139.1 MB] : NOTFINISHED 40668
Minima @ 04/06/2021 12:15:19 [139.7 MB] : START TXPOW MINING @ 126920 {"inputs":[{"coinid":"0xFEED50FEED50FEED50FEED50","address":"0x1F5215419EE7D3A2D2EAF4235E68F5072B0242E5","mxaddress":"MxD5JBKQM647J2FUXK6QRV42HVA4VQEQXF","amount":"50","tokenid":"0x00","floating":false,"storestate":true}],"outputs":[{"coinid":"0x00","address":"0xD46E553483463269BEDB03824658E9BC0417382A","mxaddress":"Mx2RXFKNEDIYZGTPW3AOBEMWHJXQCBOOBK","amount":"25","tokenid":"0x00","floating":false,"storestate":true},{"coinid":"0x00","address":"0x932CD73572F70F47C765E09F0BF54228ED1207BB","mxaddress":"MxSMWNONLS64HUPR3F4CPQX5KCFDWREB53","amount":"25","tokenid":"0x00","floating":false,"storestate":true}],"state":[],"linkhash":"0x00"}
Minima @ 04/06/2021 12:15:24 [139.1 MB] : NOTFINISHED 39535
Minima @ 04/06/2021 12:15:24 [139.6 MB] : START TXPOW MINING @ 126920 {"inputs":[{"coinid":"0xFEED50FEED50FEED50FEED50","address":"0x1F5215419EE7D3A2D2EAF4235E68F5072B0242E5","mxaddress":"MxD5JBKQM647J2FUXK6QRV42HVA4VQEQXF","amount":"50","tokenid":"0x00","floating":false,"storestate":true}],"outputs":[{"coinid":"0x00","address":"0xD46E553483463269BEDB03824658E9BC0417382A","mxaddress":"Mx2RXFKNEDIYZGTPW3AOBEMWHJXQCBOOBK","amount":"25","tokenid":"0x00","floating":false,"storestate":true},{"coinid":"0x00","address":"0x932CD73572F70F47C765E09F0BF54228ED1207BB","mxaddress":"MxSMWNONLS64HUPR3F4CPQX5KCFDWREB53","amount":"25","tokenid":"0x00","floating":false,"storestate":true}],"state":[],"linkhash":"0x00"}
Minima @ 04/06/2021 12:15:26 [151.4 MB] : TXPOW MINED! @ 126920 isBlock:false {"inputs":[{"coinid":"0xFEED50FEED50FEED50FEED50","address":"0x1F5215419EE7D3A2D2EAF4235E68F5072B0242E5","mxaddress":"MxD5JBKQM647J2FUXK6QRV42HVA4VQEQXF","amount":"50","tokenid":"0x00","floating":false,"storestate":true}],"outputs":[{"coinid":"0x00","address":"0xD46E553483463269BEDB03824658E9BC0417382A","mxaddress":"Mx2RXFKNEDIYZGTPW3AOBEMWHJXQCBOOBK","amount":"25","tokenid":"0x00","floating":false,"storestate":true},{"coinid":"0x00","address":"0x932CD73572F70F47C765E09F0BF54228ED1207BB","mxaddress":"MxSMWNONLS64HUPR3F4CPQX5KCFDWREB53","amount":"25","tokenid":"0x00","floating":false,"storestate":true}],"state":[],"linkhash":"0x00"}
Minima @ 04/06/2021 12:15:26 [153.4 MB] : NEW BALANCE : [{"tokenid":"0x00","token":"Minima","total":"1000000000","decimals":"44","confirmed":"450","unconfirmed":"0","mempool":"50","sendable":"450"},{"tokenid":"0x2D91DF11D8A19F44DD3046A77FC44EB3B705EABEE57F986F9A17EE94363A56858B0901E951076CD31BFA6A5B8DA87300C7566DAF1E7195627F539BF4C61DE47C","token":"Incentive Cash","description":"The Minima Incentive Cash Token is a reward token for participants in the Minima Incentive Program. Tokens will be awarded for a range of designated activities, and will be redeemable at mainnet on a 1:1 valuation with the Minima Coin.","icon":"https:\/\/raw.githubusercontent.com\/minima-global\/incentivecash\/main\/images\/icon.svg","proof":"https:\/\/incentive.minima.global\/incentiveCash.txt","total":"300000000","decimals":"8","script":"RETURN TRUE","coinid":"0x11BAE84EB1BE88AE6640FE2E656B327A3D338C58E33CB6E927C9898B0C070B258ED2172AD7BDD910E36FAA7F7F50405CF23A94BCEF5E866CC49D1830D87579DB","totalamount":"0.0000000000000000000000000003","scale":"36","confirmed":"28","unconfirmed":"0","mempool":"0","sendable":"0"}]
Minima @ 04/06/2021 12:15:28 [104.6 MB] : NEW BALANCE : [{"tokenid":"0x00","token":"Minima","total":"1000000000","decimals":"44","confirmed":"450","unconfirmed":"50","mempool":"0","sendable":"450"},{"tokenid":"0x2D91DF11D8A19F44DD3046A77FC44EB3B705EABEE57F986F9A17EE94363A56858B0901E951076CD31BFA6A5B8DA87300C7566DAF1E7195627F539BF4C61DE47C","token":"Incentive Cash","description":"The Minima Incentive Cash Token is a reward token for participants in the Minima Incentive Program. Tokens will be awarded for a range of designated activities, and will be redeemable at mainnet on a 1:1 valuation with the Minima Coin.","icon":"https:\/\/raw.githubusercontent.com\/minima-global\/incentivecash\/main\/images\/icon.svg","proof":"https:\/\/incentive.minima.global\/incentiveCash.txt","total":"300000000","decimals":"8","script":"RETURN TRUE","coinid":"0x11BAE84EB1BE88AE6640FE2E656B327A3D338C58E33CB6E927C9898B0C070B258ED2172AD7BDD910E36FAA7F7F50405CF23A94BCEF5E866CC49D1830D87579DB","totalamount":"0.0000000000000000000000000003","scale":"36","confirmed":"28","unconfirmed":"0","mempool":"0","sendable":"0"}]
Minima @ 04/06/2021 12:17:24 [102.8 MB] : NEW BALANCE : [{"tokenid":"0x00","token":"Minima","total":"1000000000","decimals":"44","confirmed":"500","unconfirmed":"0","mempool":"0","sendable":"500"},{"tokenid":"0x2D91DF11D8A19F44DD3046A77FC44EB3B705EABEE57F986F9A17EE94363A56858B0901E951076CD31BFA6A5B8DA87300C7566DAF1E7195627F539BF4C61DE47C","token":"Incentive Cash","description":"The Minima Incentive Cash Token is a reward token for participants in the Minima Incentive Program. Tokens will be awarded for a range of designated activities, and will be redeemable at mainnet on a 1:1 valuation with the Minima Coin.","icon":"https:\/\/raw.githubusercontent.com\/minima-global\/incentivecash\/main\/images\/icon.svg","proof":"https:\/\/incentive.minima.global\/incentiveCash.txt","total":"300000000","decimals":"8","script":"RETURN TRUE","coinid":"0x11BAE84EB1BE88AE6640FE2E656B327A3D338C58E33CB6E927C9898B0C070B258ED2172AD7BDD910E36FAA7F7F50405CF23A94BCEF5E866CC49D1830D87579DB","totalamount":"0.0000000000000000000000000003","scale":"36","confirmed":"28","unconfirmed":"0","mempool":"0","sendable":"0"}]
Minima @ 04/06/2021 12:25:01 [89.4 MB] : NEW base address created [21 / 16] : MxSX5S2JNRVQDRAGQ3CD26VSBZ55LYOCSZ
Minima @ 04/06/2021 12:25:05 [89.9 MB] : NEW base address created [6 / 17] : Mx74RW74NRERRTVMMTYSB3RNE2JHNYSSWU
Minima @ 04/06/2021 12:25:06 [91.3 MB] : START TXPOW MINING @ 126946 {"inputs":[{"coinid":"0xFEED50FEED50FEED50FEED50","address":"0x1F5215419EE7D3A2D2EAF4235E68F5072B0242E5","mxaddress":"MxD5JBKQM647J2FUXK6QRV42HVA4VQEQXF","amount":"50","tokenid":"0x00","floating":false,"storestate":true}],"outputs":[{"coinid":"0x00","address":"0x95FB2D25B1AC07101A1B10F5EAC839EF57870A59","mxaddress":"MxSX5S2JNRVQDRAGQ3CD26VSBZ55LYOCSZ","amount":"25","tokenid":"0x00","floating":false,"storestate":true},{"coinid":"0x00","address":"0xFF236FF1B124633AB193C483B8B49A49DB894AD4","mxaddress":"Mx74RW74NRERRTVMMTYSB3RNE2JHNYSSWU","amount":"25","tokenid":"0x00","floating":false,"storestate":true}],"state":[],"linkhash":"0x00"}
Minima @ 04/06/2021 12:25:11 [138.0 MB] : NOTFINISHED 36172
Minima @ 04/06/2021 12:25:11 [138.6 MB] : START TXPOW MINING @ 126948 {"inputs":[{"coinid":"0xFEED50FEED50FEED50FEED50","address":"0x1F5215419EE7D3A2D2EAF4235E68F5072B0242E5","mxaddress":"MxD5JBKQM647J2FUXK6QRV42HVA4VQEQXF","amount":"50","tokenid":"0x00","floating":false,"storestate":true}],"outputs":[{"coinid":"0x00","address":"0x95FB2D25B1AC07101A1B10F5EAC839EF57870A59","mxaddress":"MxSX5S2JNRVQDRAGQ3CD26VSBZ55LYOCSZ","amount":"25","tokenid":"0x00","floating":false,"storestate":true},{"coinid":"0x00","address":"0xFF236FF1B124633AB193C483B8B49A49DB894AD4","mxaddress":"Mx74RW74NRERRTVMMTYSB3RNE2JHNYSSWU","amount":"25","tokenid":"0x00","floating":false,"storestate":true}],"state":[],"linkhash":"0x00"}
Minima @ 04/06/2021 12:25:16 [98.2 MB] : NOTFINISHED 36398
Minima @ 04/06/2021 12:25:16 [98.7 MB] : START TXPOW MINING @ 126948 {"inputs":[{"coinid":"0xFEED50FEED50FEED50FEED50","address":"0x1F5215419EE7D3A2D2EAF4235E68F5072B0242E5","mxaddress":"MxD5JBKQM647J2FUXK6QRV42HVA4VQEQXF","amount":"50","tokenid":"0x00","floating":false,"storestate":true}],"outputs":[{"coinid":"0x00","address":"0x95FB2D25B1AC07101A1B10F5EAC839EF57870A59","mxaddress":"MxSX5S2JNRVQDRAGQ3CD26VSBZ55LYOCSZ","amount":"25","tokenid":"0x00","floating":false,"storestate":true},{"coinid":"0x00","address":"0xFF236FF1B124633AB193C483B8B49A49DB894AD4","mxaddress":"Mx74RW74NRERRTVMMTYSB3RNE2JHNYSSWU","amount":"25","tokenid":"0x00","floating":false,"storestate":true}],"state":[],"linkhash":"0x00"}
Minima @ 04/06/2021 12:25:17 [128.9 MB] : TXPOW MINED! @ 126948 isBlock:false {"inputs":[{"coinid":"0xFEED50FEED50FEED50FEED50","address":"0x1F5215419EE7D3A2D2EAF4235E68F5072B0242E5","mxaddress":"MxD5JBKQM647J2FUXK6QRV42HVA4VQEQXF","amount":"50","tokenid":"0x00","floating":false,"storestate":true}],"outputs":[{"coinid":"0x00","address":"0x95FB2D25B1AC07101A1B10F5EAC839EF57870A59","mxaddress":"MxSX5S2JNRVQDRAGQ3CD26VSBZ55LYOCSZ","amount":"25","tokenid":"0x00","floating":false,"storestate":true},{"coinid":"0x00","address":"0xFF236FF1B124633AB193C483B8B49A49DB894AD4","mxaddress":"Mx74RW74NRERRTVMMTYSB3RNE2JHNYSSWU","amount":"25","tokenid":"0x00","floating":false,"storestate":true}],"state":[],"linkhash":"0x00"}
Minima @ 04/06/2021 12:25:17 [130.9 MB] : NEW BALANCE : [{"tokenid":"0x00","token":"Minima","total":"1000000000","decimals":"44","confirmed":"500","unconfirmed":"0","mempool":"50","sendable":"500"},{"tokenid":"0x2D91DF11D8A19F44DD3046A77FC44EB3B705EABEE57F986F9A17EE94363A56858B0901E951076CD31BFA6A5B8DA87300C7566DAF1E7195627F539BF4C61DE47C","token":"Incentive Cash","description":"The Minima Incentive Cash Token is a reward token for participants in the Minima Incentive Program. Tokens will be awarded for a range of designated activities, and will be redeemable at mainnet on a 1:1 valuation with the Minima Coin.","icon":"https:\/\/raw.githubusercontent.com\/minima-global\/incentivecash\/main\/images\/icon.svg","proof":"https:\/\/incentive.minima.global\/incentiveCash.txt","total":"300000000","decimals":"8","script":"RETURN TRUE","coinid":"0x11BAE84EB1BE88AE6640FE2E656B327A3D338C58E33CB6E927C9898B0C070B258ED2172AD7BDD910E36FAA7F7F50405CF23A94BCEF5E866CC49D1830D87579DB","totalamount":"0.0000000000000000000000000003","scale":"36","confirmed":"28","unconfirmed":"0","mempool":"0","sendable":"0"}]
Minima @ 04/06/2021 12:25:37 [111.5 MB] : NEW BALANCE : [{"tokenid":"0x00","token":"Minima","total":"1000000000","decimals":"44","confirmed":"500","unconfirmed":"50","mempool":"0","sendable":"500"},{"tokenid":"0x2D91DF11D8A19F44DD3046A77FC44EB3B705EABEE57F986F9A17EE94363A56858B0901E951076CD31BFA6A5B8DA87300C7566DAF1E7195627F539BF4C61DE47C","token":"Incentive Cash","description":"The Minima Incentive Cash Token is a reward token for participants in the Minima Incentive Program. Tokens will be awarded for a range of designated activities, and will be redeemable at mainnet on a 1:1 valuation with the Minima Coin.","icon":"https:\/\/raw.githubusercontent.com\/minima-global\/incentivecash\/main\/images\/icon.svg","proof":"https:\/\/incentive.minima.global\/incentiveCash.txt","total":"300000000","decimals":"8","script":"RETURN TRUE","coinid":"0x11BAE84EB1BE88AE6640FE2E656B327A3D338C58E33CB6E927C9898B0C070B258ED2172AD7BDD910E36FAA7F7F50405CF23A94BCEF5E866CC49D1830D87579DB","totalamount":"0.0000000000000000000000000003","scale":"36","confirmed":"28","unconfirmed":"0","mempool":"0","sendable":"0"}]
Minima @ 04/06/2021 12:26:35 [118.4 MB] : NEW BALANCE : [{"tokenid":"0x00","token":"Minima","total":"1000000000","decimals":"44","confirmed":"550","unconfirmed":"0","mempool":"0","sendable":"550"},{"tokenid":"0x2D91DF11D8A19F44DD3046A77FC44EB3B705EABEE57F986F9A17EE94363A56858B0901E951076CD31BFA6A5B8DA87300C7566DAF1E7195627F539BF4C61DE47C","token":"Incentive Cash","description":"The Minima Incentive Cash Token is a reward token for participants in the Minima Incentive Program. Tokens will be awarded for a range of designated activities, and will be redeemable at mainnet on a 1:1 valuation with the Minima Coin.","icon":"https:\/\/raw.githubusercontent.com\/minima-global\/incentivecash\/main\/images\/icon.svg","proof":"https:\/\/incentive.minima.global\/incentiveCash.txt","total":"300000000","decimals":"8","script":"RETURN TRUE","coinid":"0x11BAE84EB1BE88AE6640FE2E656B327A3D338C58E33CB6E927C9898B0C070B258ED2172AD7BDD910E36FAA7F7F50405CF23A94BCEF5E866CC49D1830D87579DB","totalamount":"0.0000000000000000000000000003","scale":"36","confirmed":"28","unconfirmed":"0","mempool":"0","sendable":"0"}]
Minima @ 04/06/2021 13:51:18 [267.9 MB] : Request missing TxPoW in block 127192 0x000040EB9DE69A6818137175EBA2B6850A5DD318FCA9D0BCFFDB5248D41901FFB773939BE397B51A02F07D2F3A1F72EDD38BF44660B4E382235DBB11698E31B1
Minima @ 04/06/2021 14:01:17 [246.5 MB] : Request missing TxPoW in block 127218 0x000016E81C6F75C8AE9219BD47EA7DEA3A3484587B729CE97B23D21E14F06B927A5C7FE921B7E0CCDC6202FD66770953E3435921BCE7B7E0553145D3CFB1A01E
Minima @ 04/06/2021 14:10:21 [89.3 MB] : START TXPOW MINING @ 127250 {"inputs":[{"coinid":"0xFEED50FEED50FEED50FEED50","address":"0x1F5215419EE7D3A2D2EAF4235E68F5072B0242E5","mxaddress":"MxD5JBKQM647J2FUXK6QRV42HVA4VQEQXF","amount":"50","tokenid":"0x00","floating":false,"storestate":true}],"outputs":[{"coinid":"0x00","address":"0x01E613E51CF5899B7BF73C0FC2E6D571D59EB76D","mxaddress":"MxAHTBHZI46WEZW67XHQH4FZWVOHKZ5N3N","amount":"25","tokenid":"0x00","floating":false,"storestate":true},{"coinid":"0x00","address":"0x6C1E9E9DF189FD625F6198DBF95E64AAEA6723F8","mxaddress":"MxNQPJ5HPRRH6WEX3BTDN7SXTEVLVGOI7Y","amount":"25","tokenid":"0x00","floating":false,"storestate":true}],"state":[],"linkhash":"0x00"}
Minima @ 04/06/2021 14:10:24 [114.7 MB] : TXPOW MINED! @ 127250 isBlock:false {"inputs":[{"coinid":"0xFEED50FEED50FEED50FEED50","address":"0x1F5215419EE7D3A2D2EAF4235E68F5072B0242E5","mxaddress":"MxD5JBKQM647J2FUXK6QRV42HVA4VQEQXF","amount":"50","tokenid":"0x00","floating":false,"storestate":true}],"outputs":[{"coinid":"0x00","address":"0x01E613E51CF5899B7BF73C0FC2E6D571D59EB76D","mxaddress":"MxAHTBHZI46WEZW67XHQH4FZWVOHKZ5N3N","amount":"25","tokenid":"0x00","floating":false,"storestate":true},{"coinid":"0x00","address":"0x6C1E9E9DF189FD625F6198DBF95E64AAEA6723F8","mxaddress":"MxNQPJ5HPRRH6WEX3BTDN7SXTEVLVGOI7Y","amount":"25","tokenid":"0x00","floating":false,"storestate":true}],"state":[],"linkhash":"0x00"}
Minima @ 04/06/2021 14:10:24 [116.7 MB] : NEW BALANCE : [{"tokenid":"0x00","token":"Minima","total":"1000000000","decimals":"44","confirmed":"550","unconfirmed":"0","mempool":"50","sendable":"550"},{"tokenid":"0x2D91DF11D8A19F44DD3046A77FC44EB3B705EABEE57F986F9A17EE94363A56858B0901E951076CD31BFA6A5B8DA87300C7566DAF1E7195627F539BF4C61DE47C","token":"Incentive Cash","description":"The Minima Incentive Cash Token is a reward token for participants in the Minima Incentive Program. Tokens will be awarded for a range of designated activities, and will be redeemable at mainnet on a 1:1 valuation with the Minima Coin.","icon":"https:\/\/raw.githubusercontent.com\/minima-global\/incentivecash\/main\/images\/icon.svg","proof":"https:\/\/incentive.minima.global\/incentiveCash.txt","total":"300000000","decimals":"8","script":"RETURN TRUE","coinid":"0x11BAE84EB1BE88AE6640FE2E656B327A3D338C58E33CB6E927C9898B0C070B258ED2172AD7BDD910E36FAA7F7F50405CF23A94BCEF5E866CC49D1830D87579DB","totalamount":"0.0000000000000000000000000003","scale":"36","confirmed":"28","unconfirmed":"0","mempool":"0","sendable":"0"}]
Minima @ 04/06/2021 14:10:41 [94.4 MB] : NEW BALANCE : [{"tokenid":"0x00","token":"Minima","total":"1000000000","decimals":"44","confirmed":"550","unconfirmed":"50","mempool":"0","sendable":"550"},{"tokenid":"0x2D91DF11D8A19F44DD3046A77FC44EB3B705EABEE57F986F9A17EE94363A56858B0901E951076CD31BFA6A5B8DA87300C7566DAF1E7195627F539BF4C61DE47C","token":"Incentive Cash","description":"The Minima Incentive Cash Token is a reward token for participants in the Minima Incentive Program. Tokens will be awarded for a range of designated activities, and will be redeemable at mainnet on a 1:1 valuation with the Minima Coin.","icon":"https:\/\/raw.githubusercontent.com\/minima-global\/incentivecash\/main\/images\/icon.svg","proof":"https:\/\/incentive.minima.global\/incentiveCash.txt","total":"300000000","decimals":"8","script":"RETURN TRUE","coinid":"0x11BAE84EB1BE88AE6640FE2E656B327A3D338C58E33CB6E927C9898B0C070B258ED2172AD7BDD910E36FAA7F7F50405CF23A94BCEF5E866CC49D1830D87579DB","totalamount":"0.0000000000000000000000000003","scale":"36","confirmed":"28","unconfirmed":"0","mempool":"0","sendable":"0"}]
Minima @ 04/06/2021 14:11:21 [235.7 MB] : NEW BALANCE : [{"tokenid":"0x00","token":"Minima","total":"1000000000","decimals":"44","confirmed":"600","unconfirmed":"0","mempool":"0","sendable":"600"},{"tokenid":"0x2D91DF11D8A19F44DD3046A77FC44EB3B705EABEE57F986F9A17EE94363A56858B0901E951076CD31BFA6A5B8DA87300C7566DAF1E7195627F539BF4C61DE47C","token":"Incentive Cash","description":"The Minima Incentive Cash Token is a reward token for participants in the Minima Incentive Program. Tokens will be awarded for a range of designated activities, and will be redeemable at mainnet on a 1:1 valuation with the Minima Coin.","icon":"https:\/\/raw.githubusercontent.com\/minima-global\/incentivecash\/main\/images\/icon.svg","proof":"https:\/\/incentive.minima.global\/incentiveCash.txt","total":"300000000","decimals":"8","script":"RETURN TRUE","coinid":"0x11BAE84EB1BE88AE6640FE2E656B327A3D338C58E33CB6E927C9898B0C070B258ED2172AD7BDD910E36FAA7F7F50405CF23A94BCEF5E866CC49D1830D87579DB","totalamount":"0.0000000000000000000000000003","scale":"36","confirmed":"28","unconfirmed":"0","mempool":"0","sendable":"0"}]
Minima @ 04/06/2021 14:18:53 [84.3 MB] : RPCHANDLER : java.util.NoSuchElementException 
Minima @ 04/06/2021 14:20:28 [86.1 MB] : NEW base address created [3 / 18] : MxX4CULSCIOBFV5B4IIGKCXHL6DO3WHA72
Minima @ 04/06/2021 14:20:28 [87.0 MB] : START TXPOW MINING @ 127280 {"inputs":[{"coinid":"0xFEED50FEED50FEED50FEED50","address":"0x1F5215419EE7D3A2D2EAF4235E68F5072B0242E5","mxaddress":"MxD5JBKQM647J2FUXK6QRV42HVA4VQEQXF","amount":"50","tokenid":"0x00","floating":false,"storestate":true}],"outputs":[{"coinid":"0x00","address":"0xBF0545C848704B5E878841942B9D7E1BB76383FA","mxaddress":"MxX4CULSCIOBFV5B4IIGKCXHL6DO3WHA72","amount":"25","tokenid":"0x00","floating":false,"storestate":true},{"coinid":"0x00","address":"0x6C1E9E9DF189FD625F6198DBF95E64AAEA6723F8","mxaddress":"MxNQPJ5HPRRH6WEX3BTDN7SXTEVLVGOI7Y","amount":"25","tokenid":"0x00","floating":false,"storestate":true}],"state":[],"linkhash":"0x00"}
Minima @ 04/06/2021 14:20:33 [163.0 MB] : NOTFINISHED 38845
Minima @ 04/06/2021 14:20:33 [163.6 MB] : START TXPOW MINING @ 127282 {"inputs":[{"coinid":"0xFEED50FEED50FEED50FEED50","address":"0x1F5215419EE7D3A2D2EAF4235E68F5072B0242E5","mxaddress":"MxD5JBKQM647J2FUXK6QRV42HVA4VQEQXF","amount":"50","tokenid":"0x00","floating":false,"storestate":true}],"outputs":[{"coinid":"0x00","address":"0xBF0545C848704B5E878841942B9D7E1BB76383FA","mxaddress":"MxX4CULSCIOBFV5B4IIGKCXHL6DO3WHA72","amount":"25","tokenid":"0x00","floating":false,"storestate":true},{"coinid":"0x00","address":"0x6C1E9E9DF189FD625F6198DBF95E64AAEA6723F8","mxaddress":"MxNQPJ5HPRRH6WEX3BTDN7SXTEVLVGOI7Y","amount":"25","tokenid":"0x00","floating":false,"storestate":true}],"state":[],"linkhash":"0x00"}
Minima @ 04/06/2021 14:20:38 [124.9 MB] : NOTFINISHED 38729
Minima @ 04/06/2021 14:20:38 [126.9 MB] : START TXPOW MINING @ 127282 {"inputs":[{"coinid":"0xFEED50FEED50FEED50FEED50","address":"0x1F5215419EE7D3A2D2EAF4235E68F5072B0242E5","mxaddress":"MxD5JBKQM647J2FUXK6QRV42HVA4VQEQXF","amount":"50","tokenid":"0x00","floating":false,"storestate":true}],"outputs":[{"coinid":"0x00","address":"0xBF0545C848704B5E878841942B9D7E1BB76383FA","mxaddress":"MxX4CULSCIOBFV5B4IIGKCXHL6DO3WHA72","amount":"25","tokenid":"0x00","floating":false,"storestate":true},{"coinid":"0x00","address":"0x6C1E9E9DF189FD625F6198DBF95E64AAEA6723F8","mxaddress":"MxNQPJ5HPRRH6WEX3BTDN7SXTEVLVGOI7Y","amount":"25","tokenid":"0x00","floating":false,"storestate":true}],"state":[],"linkhash":"0x00"}
Minima @ 04/06/2021 14:20:43 [113.1 MB] : NOTFINISHED 40050
Minima @ 04/06/2021 14:20:43 [113.6 MB] : START TXPOW MINING @ 127282 {"inputs"

**Comment by jazminrib** [comment]
Actually not sure if this is a bug or a feature, but I don't recall this happening in previous versions and feels like the history should only show the tx once it's confirmed

**Comment by eurobuddha** [comment]
I think the history is faster to update will discuss with the devs

**Comment by eliasnemr** [comment]
We are aware of this bug and is being worked on.  The reason this happens is once the coin enters the mempool that's when history registers the transaction and not after it's in the network.. so if it fails in the mempool then you still see it in history.
