### ISSUE TITLE
Wallet > Send : Form is cleared if "Balance Updated" notification pops up

### ISSUE THREAD

**Issue by jazminrib** [minima-global/Minima#244]
Issue Impact: Minor
Device Manufacturer: Samsung
Device Model: S10
Device OS: Android
Device OS Version: 11
Application Version: apk: v0.98.20 wallet version 1.1.2

**What Happened?:** On the Send page, if a tx is being processed in the background and the "Balance updated" popup appears it clears the form, so the address, amount, and message is cleared.

**What Did You Expect To Happen?** The address, amount and balance would stay there if the pop up appears.

**Steps to recreate:** Hit Gimme 50 > Go to Send page and create a tx but do not send > wait for the "balance updated" pop up to appear > form is cleared.

Not sure if logs are required for this one but let me know if they are. 

![CreatingTX](https://user-images.githubusercontent.com/60537663/120829939-e3393000-c555-11eb-9754-64a0175d8c1e.jpg)
![BalanceUpdatedandFormCleared](https://user-images.githubusercontent.com/60537663/120829943-e59b8a00-c555-11eb-959e-c3f447047f5a.jpg)

**Comment by eliasnemr** [comment]
Hi Jazmin,

I know why this is happening, No logs needed.

Thanks!

Have a good weekend

Elias

**Comment by eliasnemr** [comment]
This is now fixed in v1.1.3, form is no longer cleared when there is a balance change

**Comment by eurobuddha** [comment]
closing
