### ISSUE TITLE
Wallet > Terminal : Trying to copy anything returns my wallet address 

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#245]
Issue Impact: Minor
Device Manufacturer: Samsung
Device Model: S10
Device OS: Android
Device OS Version: 11
Application Version: apk: v0.98.20 wallet version 1.1.2

**What Happened?:** Open the Terminal from within the wallet, type any command e.g. Help or Balance and try to copy any of the outputs, it always copies my wallet address to the clipboard, not the content I highlight. Happens on the phone and in the web. 
This does not happen if you access the separate terminal app from the MiniDapp Hub, where the copy/paste works correctly.

**What Did You Expect To Happen?** The content I highlight and copy is copied to my clipboard

**Steps to recreate:** Open the wallet > go to Terminal > enter a command e.g. Help/Balance > Highlight content and copy > Paste somewhere else > my wallet address (confirmed by checking the Receive page) is returned each time even if it was not the last thing on my clipboard. 

Screenshot1: Highlighted text copied
Screenshot2: Result of pasting 
Screenshot3: Confirming the output is my wallet address 

![WalletTerminal](https://user-images.githubusercontent.com/60537663/120832412-8b4ff880-c558-11eb-83ce-3b9d2324b347.jpg)
![WalletAddress](https://user-images.githubusercontent.com/60537663/120832430-8f7c1600-c558-11eb-8bf2-b18faf5a839b.jpg)
![ReceiveAddress](https://user-images.githubusercontent.com/60537663/120832577-b9353d00-c558-11eb-8739-1cbb5f63cf5d.jpg)

**Comment by jazminrib** [comment]
Was a fix applied for this? It appears to be working now in wallet 1.1.4

**Comment by eliasnemr** [comment]
Yes there has been.

**Comment by jazminrib** [comment]
Great, then this can be closed, thanks.
