### ISSUE TITLE
Sending Transaction status failed, opperation time out.

### ISSUE THREAD

**Issue by BoldorXL** [minima-global/Minima#247]
Good morning Support,

This is a Minor issue

Device Manufacturer: Samsung
Device Model: Galaxi S20+ 5G
Divice OS: Android 
Device OS Version: 11
Application Version: 3.1
Event, Transaction Failed when sending Minima, getting a operation timeout
 I expected  I could sent Minima to a other wallet
Steps to Recreate Issue: 
Close the app and window taps, start app, select sending, fill in info, press sent, getting the same issue.

What I've noticed is that at times when it failed the transaction is taking longer than normal.

PS: After the video stops there was a conform balance chance after pressing ok

https://user-images.githubusercontent.com/73369734/120897526-f5cf6a00-c626-11eb-90da-f4a9606823fc.mp4

[Transaction fail time out 3_21.txt](https://github.com/minima-global/Minima/files/6602804/Transaction.fail.time.out.3_21.txt)

**Comment by eurobuddha** [comment]
@BoldorXL please remember to include logs with EVERY issue submitted, it is the only way we can analyse what's happening.

does the txn get sent or nothing is sent?

**Comment by BoldorXL** [comment]
> 
> 
> @BoldorXL please remember to include logs with EVERY issue submitted, it is the only way we can analyse what's happening.
> 
> does the txn get sent or nothing is sent?

Yes

**Comment by BoldorXL** [comment]
Got the same issue again, can't reproduce it. Was sending one after  the other tokens to my contact list
![Screenshot_20210609-090826_Brave](https://user-images.githubusercontent.com/73369734/121314249-7502bd80-c907-11eb-99ca-0cc2d58a71a2.jpg)
[Transaction fail 9-6-21.txt](https://github.com/minima-global/Minima/files/6621969/Transaction.fail.9-6-21.txt)
