### ISSUE TITLE
Wallet, Terminal and IC do not open after receiving token

### ISSUE THREAD

**Issue by jazminrib** [minima-global/Minima#248]
Issue Impact: Critical
Device Manufacturer: Samsung
Device Model: S10
Device OS: Android
Device OS Version: 11
Application Version: apk: v0.98.20 wallet version 1.1.2

What Happened?: Eurobuddha sent one of his special NFTs, which resulted in a JSON syntax error message. The error then disappears and the wallet hangs on that screen and does not open. Terminal and incentive cash also do not open. I then rebooted my phone but there is no change in behaviour.

What Did You Expect To Happen? Wallet opens and can see new tokens.

Steps to recreate: get Eurobuddha to send one of his NFTs....

I've attached two sets of logs, before and after rebooting my phone. The second set of logs says that IC cash collection was missed too. 

Screenshot1: JSON error and wallet not opening 
Screenshot2: Terminal not opening
Screenshot3: Incentive Cash not opening

![Screenshot_20210605-190537_Brave](https://user-images.githubusercontent.com/60537663/120902429-5024f680-c638-11eb-9a2b-5e184d92f0f8.jpg)
![Screenshot_20210605-192608_Brave](https://user-images.githubusercontent.com/60537663/120902431-55824100-c638-11eb-9309-5fcf79d361eb.jpg)
![Screenshot_20210605-193727_Brave](https://user-images.githubusercontent.com/60537663/120902432-57e49b00-c638-11eb-8556-d62514ae0fcd.jpg)
[Minima Logs before phone reboot.docx](https://github.com/minima-global/Minima/files/6603054/Minima.Logs.before.phone.reboot.docx)
[Minima Logs after phone reboot.docx](https://github.com/minima-global/Minima/files/6603055/Minima.Logs.after.phone.reboot.docx)

**Comment by eurobuddha** [comment]
solved with 98.24 upgrade
