### ISSUE TITLE
Incentive Cash FAQ says "You will earn 2 Minima a day..."

### ISSUE THREAD

**Issue by jazminrib** [minima-global/Minima#250]
Hi team, 

The FAQs in Incentive Cash say you will earn 2 Minima a day when the amount is 1 a day. 

![IncentiveCash](https://user-images.githubusercontent.com/60537663/120904617-00006100-c645-11eb-91be-b182cb502c69.jpg)

**Comment by eurobuddha** [comment]
nice spot

**Comment by eliasnemr** [comment]
This is fixed in v1.0.43

**Comment by eurobuddha** [comment]
fixed, closing

**Comment by jazminrib** [comment]
Hi,

The new version of IC 1.0.43 says "You will earn 1 Minima per week". Is this correct? 
![image](https://user-images.githubusercontent.com/60537663/122255177-c7bf1500-cec5-11eb-8535-bef066612e6d.png)

Thanks,
Jazmin

**Comment by eliasnemr** [comment]
Nope, it should be 7 a week.. will be fixed in next version

**Comment by jazminrib** [comment]
ah you were too quick to respond!  Eurobuddha asked me to raise this as a new ticket since this one is closed...
