### ISSUE TITLE
Jpeg cant be used 

### ISSUE THREAD

**Issue by BoldorXL** [minima-global/Minima#252]
Hello Support, 

Issue Impact: Minor Issue 

Device Manufacturer: Samsung
Device Model: Galaxi S20+ 5G
Divice OS: Android 
Device OS Version: 11
Application Version: 3.1
When making a token and pasting a link for it it's showing a error message. Used a jpeg file and I see that's not supported. But jpg an jpeg are the same so I thought is must work.
I started over again but I got the same error.

![Screenshot_20210606-131500_Brave](https://user-images.githubusercontent.com/73369734/120922540-16043500-c6ca-11eb-8206-f831d6543548.jpg)

**Comment by BoldorXL** [comment]
Didn't log save the log file at the time bc it wasn't working. So no coins were made ore sent. Now attacht the log file
[JPeg can't be used.txt](https://github.com/minima-global/Minima/files/6604420/JPeg.can.t.be.used.txt)

**Comment by eurobuddha** [comment]
excellet catch .jpg and .jpeg are identical so it should be allowed/valid

**Comment by eliasnemr** [comment]
This is now fixed in wallet v1.1.3

**Comment by Sw1fty** [comment]
Issue was fixed
