### ISSUE TITLE
Enhancement: Auto-Refresh in History

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#254]
Hi team, 

It would be nice to have the History page auto-refresh, at the moment you either have to refresh the browser or flick to another page, then come back into History (this can actually take a couple of times switching to a different page and back before the History page is updated even if the transaction was a while ago. )

Next best thing would be a little refresh button at the top. 

Thanks!
Jazmin

**Comment by eliasnemr** [comment]
This is a nice to have.  We have removed auto refresh from history recently due to  unnecessary heavy background work

**Comment by jazminrib** [comment]
That makes sense.
Perhaps a Refresh icon at the top would be a good compromise so it doesn't have to auto refresh but user also doesn't have to manually refresh the webpage. The usual method of dragging the page down to refresh also doesn't work here so the workaround is usually closing/reopening the wallet or clicking in the URL bar and refreshing that way which are both not ideal.

Cheers

**Comment by Sw1fty** [comment]
Sounds like something we should change in minima node to make getting updates to the history easier
