### ISSUE TITLE
Wallet > Balance transactions stuck after changing timezone

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#255]
Issue Impact: Critical
Device Manufacturer: Samsung
Device Model: S10
Device OS: Android
Device OS Version: 11
Application Version: apk: v0.98.24 wallet version 1.1.2

What Happened?: A series of unfortunately events....
I changed my timezone to GMT + 3, hit Gimme 50, but the tx stayed flashing in the mempool. The timestamps in the History change to the new timezone but the logs timestamps did not change.
I then received tokens which show in my History as confirmed but not in my Balance.
I then changed back to UK time GMT+1 and tried to flush the mempool (hard) which didn't clear it but created duplicate entries in History.
Subsequent receiving transactions: these are showing in my History as complete but Minima sent to me gets added to the mempool and custom tokens do not appear at all in the Balance screen. 
Subsequent outgoing transactions: I tried to send Minima - it gets removed from the mempool amount. When I try to send a custom token the whole amount goes into the mempool which then gets stuck and remains flashing so I can no longer send any more of that token.
Tried to flush the mempool again which caused the new transactions to get duplicated in the History. 

What Did You Expect To Happen? Minima would change to new timezone and Gimme 50 tx would go through. Able to see newly received tokens in my Balance. Sent tokens would not get stuck.

Steps to recreate: 
1. Disable automatic timezone detection on phone, set it to another time zone (this was ahead of the UK), 
2. Open wallet > Try gimme 50
3. Receive custom tokens (check History vs Balance)
4. Return to UK timezone
5. Run Flushmempool -hard
6. Receive more tokens and flush the mempool again

screenshot 1: Before changing the timezone
screenshot 2: After changing the timezone - the timestamps in History are updated correctly and my phone time has changed +2 hours (GMT +3)
screen recording 3: end state after returning to UK time and attempts to receive/send tokens and flush the mempool.
shows Vote token is not sendable, duplicate entries in History and Balance does not show newly recieved tokens e.g. Van Gogh or Fork tokens which are visible in the History.

![BeforeTimezoneChange](https://user-images.githubusercontent.com/60537663/120941949-8a1bf880-c71d-11eb-8426-6deebdf2f60b.jpg)
![AfterTimezoneChange](https://user-images.githubusercontent.com/60537663/120941952-8d16e900-c71d-11eb-97bc-35430d665fdc.jpg)

https://user-images.githubusercontent.com/60537663/120942168-f3503b80-c71e-11eb-9662-3b63c0efa29c.mp4

Two sets of logs attached, sorry I think there is some time missing between them. The timestamps in the logs are all UK time.

[Minima Logs1.docx](https://github.com/minima-global/Minima/files/6605027/Minima.Logs1.docx)
[Minima Logs2.docx](https://github.com/minima-global/Minima/files/6605029/Minima.Logs2.docx)

Sorry a lot going on there, let me know if you need more info!

**Comment by jazminrib** [comment]
Morning,

I just noticed that my node is stuck at 21:04 yesterday, block 317108.
See terminal output of Status this morning.

![Screenshot_20210607-080113_Brave](https://user-images.githubusercontent.com/60537663/120973264-9bd5be00-c766-11eb-9602-1a59d4fc2a5b.jpg)
![Screenshot_20210607-080119_Brave](https://user-images.githubusercontent.com/60537663/120973280-a001db80-c766-11eb-8c36-76ae90f47b17.jpg)

I tried to send the remaining Minima that shows as stuck in my mempool but I got two errors:
First attempt: 
![Screenshot_20210607-075651_Brave](https://user-images.githubusercontent.com/60537663/120973672-25858b80-c767-11eb-8fbd-b79bc54989df.jpg)

Second attempt:
![Screenshot_20210607-075729_Brave](https://user-images.githubusercontent.com/60537663/120973725-30d8b700-c767-11eb-9592-e3765aa20382.jpg)

Logs: 
[Minima Logs attempt to send all Minima in mempool_210607_075844.txt](https://github.com/minima-global/Minima/files/6606564/Minima.Logs.attempt.to.send.all.Minima.in.mempool_210607_075844.txt)

**Comment by jazminrib** [comment]
I restarted my phone and it's now caught up to the current time and the tokens are all showing in my Balance as expected.  Is there a way to force this resync without having to reboot my phone? 

I now have triple instances of txs showing in my History however.
![Screenshot_20210607-085724_Brave](https://user-images.githubusercontent.com/60537663/120980830-e6f3cf00-c76e-11eb-8aad-1b697acd709f.jpg)

Logs after phone reboot.
[Minima Logs resync_210607_085917.txt](https://github.com/minima-global/Minima/files/6606988/Minima.Logs.resync_210607_085917.txt)

**Comment by jazminrib** [comment]
Sorry I forgot to mention that I did select a couple of time zones between 21:00 and 21:17 at which point I settled on GMT+3. So the 21:04 block I got stuck on probably coincides with the first change in timezone. The only actions I took before 21:17 was trying Gimme50 when the timezone was 1 hour behind UK. This resulted in the "you can only use gimme50 once every 10 mins" - I noticed that the time coincided with when I had done Gimme50 one hour earlier. 

21:18 is then when I did the Gimme50 in the GMT+3 timezone.

Hope this isn't too confusing!

**Comment by eurobuddha** [comment]
My understanding is that by time travelling the protocol finds and follows the wrong branch. A reboot in the correct timezone fixes this.
