### ISSUE TITLE
Different date and time stap in log, history showing same transaction even afterxrebootand hard flush 

### ISSUE THREAD

**Issue by BoldorXL** [minima-global/Minima#256]
Hello Support, 

Issue Impact: Minor Issue 

Device Manufacturer: Samsung
Device Model: Galaxi S20+ 5G
Divice OS: Android 
Device OS Version: 11
Application Version: 3.1
What Happend? When playing around with changing the date and time on my phone I wasn't able to use the gimmi bc the system was saying I can only collect ones every 10 min. Was expecting I was able to bc of the change in date and time.
After setting time and date back correctly all seemed fine but this morning found oud that the balance kept flashing and history was showing double transactions and mempool was showing more than 50. Used a hard flush, still flashing and mempool not empty. Closed app and taps, restart, still flashing mempool not empty, history still double transactions. Checking block count it was clear I wasn't on the richt block.Reboot my phone, right block again, mempool empty but in the log a line saying Trying to copy a file that does not exist.
Was expecting that after the reboot all was back to normal again.
After using the gimme again I got a transasction time out again. Using gimmi again didn't give the same error
[Date and time change and not syced.txt](https://github.com/minima-global/Minima/files/6607365/Date.and.time.change.and.not.syced.txt)
![Screenshot_20210607-103953_Brave](https://user-images.githubusercontent.com/73369734/120988537-f4b15080-c77e-11eb-9b54-b639d3525054.jpg)
![Screenshot_20210607-103440_Brave](https://user-images.githubusercontent.com/73369734/120988964-52de3380-c77f-11eb-9373-35418422296e.jpg)
[Transactions error.txt](https://github.com/minima-global/Minima/files/6607390/Transactions.error.txt)

https://user-images.githubusercontent.com/73369734/120989229-9afd5600-c77f-11eb-98c6-e4711b8827b0.mp4

**Comment by eurobuddha** [comment]
I believe blocktime is king protocol wise and the history time/date data shown in the wallet is system generated. Will check. thank you
