### ISSUE TITLE
Date and time set to futher changes insensitive date and time

### ISSUE THREAD

**Issue by BoldorXL** [minima-global/Minima#257]
Issue Impact: Minor Issue 

Device Manufacturer: Samsung
Device Model: Galaxi S20+ 5G
Divice OS: Android 
Device OS Version: 11
Application Version: 3.1
What Happend? When setting the date and time to the future the date and time was changed in the incentive app. Was expecting something to happen bc I set it just before the first do date. Gimmi was working fine, setting g date and time back to normal Gimmi is not allowing me to use it, of course bc there is a time stamp of the futher. Have to reboot to get it working again. There are 2 vote tokens showing in history and 1 in balans. After reboot that should be fine as well, if not ill ad it as well.
![Screenshot_20210611-104125_Brave](https://user-images.githubusercontent.com/73369734/120993438-ceda7a80-c783-11eb-80b8-fbc18a87d8c0.jpg)
[Date time change further .txt](https://github.com/minima-global/Minima/files/6607658/Date.time.change.further.txt)
![Screenshot_20210611-104013_Brave](https://user-images.githubusercontent.com/73369734/120993516-e154b400-c783-11eb-8836-e1ffdc97992b.jpg)
![Screenshot_20210611-104008_Brave](https://user-images.githubusercontent.com/73369734/120993535-e6196800-c783-11eb-82a7-e38e496752e0.jpg)
![Screenshot_20210611-104002_Brave](https://user-images.githubusercontent.com/73369734/120993568-efa2d000-c783-11eb-8382-f4f989c81474.jpg)

**Comment by BoldorXL** [comment]
[Date time change further .txt](https://github.com/minima-global/Minima/files/6607672/Date.time.change.further.txt)

**Comment by BoldorXL** [comment]
After reboot it's still showing 2 vote token transactions in history, gimmi it working fine again
[Log after reboot still 2 vote in history .txt](https://github.com/minima-global/Minima/files/6607879/Log.after.reboot.still.2.vote.in.history.txt)
![Screenshot_20210611-104125_Brave](https://user-images.githubusercontent.com/73369734/120997631-a9e80680-c787-11eb-88d6-4634d982b2d5.jpg)

**Comment by glowkeeper** [comment]
Hi @BoldorXL!

The incentive cash minidapp definitely **SHOULD NOT COLLECT** if you act dishonestly and change the date on your system; collections are wholly dependant on the Minima blocks.

The date _displayed_ is relative to the system date you set, so if that date's wrong, well, the relative date will be wrong, too. 

In other words, I'm pretty sure this is correct behaviour for the incentive cash minidapp. Desirable, even ;)
