### ISSUE TITLE
APK crashing following wallet receiving large file token

### ISSUE THREAD

**Issue by rafaroberto** [minima-global/Minima#260]
Issue Impact: High
Device Manufacturer: Huawei 
Device Model: P20Pro 
Device OS: Android
Device OS Version: 11
Application Version: apk: v0.98.24 wallet version 1.1.2
What Happened?: After receiving a token containing 500MB file the wallet froze and shortly after crashed the APK. APK would restart by itself and run without any issues. The following dapps would open and work without any problems: Incentive Cash, Storefront, Terminal. 
Upon opening the Wallet the dapp would freeze then APK would crash and shut down and the handset would freeze momentarily. 
On advice from Barry I've attempted to clear the token out of the wallet through the Terminal command. Eventually successfully doing so. 

Once I've logged back to the wallet the history showed the token being received three times (the same hash) and sent out once. 

Screenshots attached. 

What Did You Expect To Happen? Wallet being able to open with tokens including large file

Steps to Recreate Issue: Reopening wallet 5 time following APK crashing after attempting opening the wallet 

Logs to follow un comments by the Master Jedi himself. Barry. 

![Screenshot_20210607_182617_com brave browser](https://user-images.githubusercontent.com/85311500/121065562-ceaca000-c7c0-11eb-8fa7-772eec918df0.jpg)

**Comment by eurobuddha** [comment]
[raf.txt](https://github.com/minima-global/Minima/files/6611200/raf.txt)

**Comment by eurobuddha** [comment]
the same token (id 0x08DC25EA26776521F1080EA58CB09D06FA32B1E7B9AC14E2452390105ADB24786F1770CDEAEDD44DB257C46CF5D2909071BD951E2D1E316179678B2626332F10) Universe with 500mb custom icon, made S10+ apk proxy wallet on chrome grind and almost stop. once removed from wallet issue cleared.
