### ISSUE TITLE
Wallet > Contacts: No way of seeing contacts description

### ISSUE THREAD

**Issue by jazminrib** [minima-global/Minima#261]
Hi,

There is a description field available when creating a new contact but no way to see the description after the contact had been created. 

Thanks
Jazmin

**Comment by eurobuddha** [comment]
will be done. or removed

**Comment by eliasnemr** [comment]
Now available in wallet v1.1.3, contact info page includes editing/updating icon, description

**Comment by jazminrib** [comment]
Tested and confirm that contact description can now be seen

**Comment by eurobuddha** [comment]
fixed in 1.1.3 confirmed by @jazminrib
