### ISSUE TITLE
Wallet > Contacts Enhancement: Swipe right to edit

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#262]
Hi,

Would be nice to be able to edit contacts in case of mistakes/change of address/change of image url.
Swipe left is currently used to copy the address, could Edit be added as the swipe right feature? 

Thanks,
Jazmin

**Comment by glowkeeper** [comment]
@eliasnemr - what dya reckon?

**Comment by eliasnemr** [comment]
Editing description & avatar now available in wallet v1.1.3

**Comment by jazminrib** [comment]
Tested and confirm that contact description and avatar can be changed, thanks :)
