### ISSUE TITLE
Enhancement - Terminal (and other dapps) 

### ISSUE THREAD

**Issue by rafaroberto** [minima-global/Minima#263]
Hi Guys,

I feel like a unified way or showing pop ups for various actions (mining, balance changes etc) should be shown across all dapps coming from the Minima brand.
I know that terminal is still on the old version but probably worth keeping in mind. 

Attached screenshot of Terminal with two different types of pop ups.

![Screenshot_20210607_181303_com brave browser](https://user-images.githubusercontent.com/85311500/121093521-0f1e1500-c7e5-11eb-9464-017e31f95eff.jpg)

**Comment by eurobuddha** [comment]
makes sense to update all the core miniDapps to have a consistent look and feels with regard to pop ups and alerts. Great suggestion.

**Comment by eliasnemr** [comment]
This has been discussed 6 months ago and we have to conclusion that we prefer that each minidapp overrides the mining message giving the minidapps their own feel & touch.  We agree that perhaps the terminal needs a design upgrade and is being worked on.
