### ISSUE TITLE
Wallet > Send Enhancement: Tokens to be filtered/searchable

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#269]
Hi guys, 

As an enhancement, it would be nice if the token list would filter as you type or allow you to search by name/token ID. 
Our list of tokens is getting very long!

Thanks
Jazmin

**Comment by eurobuddha** [comment]
excellent suggestion, especially important when you have hundreds of different tokens in your wallet

**Comment by eliasnemr** [comment]
Now added to Wallet v1.1.7
