### ISSUE TITLE
Question: Wallet > Status - What is the Tip address for?

### ISSUE THREAD

**Issue by jazminrib** [minima-global/Minima#270]
Hi guys, 

What is the Tip address for in the Status panel?

![Status](https://user-images.githubusercontent.com/60537663/121552412-5c2e0100-ca08-11eb-9dbf-4d0c0ee9b223.jpg)

Thanks
Jazmin

**Comment by eliasnemr** [comment]
Tip address is the hash address of the block at the tip of the chain
