### ISSUE TITLE
Wallet > History: Rename Recipient Address to Sender Address

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#271]
Hello,

In the transaction details in History, as I understand it, the Inputs are the senders UTXOs which are used as inputs to the transaction and the Outputs have 2 outgoing addresses - one is the address of the receiver (recipient) and the other is the sender's address used for the returning utxo.

The confusing thing is having "Recipient Address" in the input section, when it is not the recipient's address but the senders. 

Perhaps the labelling can be renamed: 
Inputs: Sender Address
Outputs:  Recipient/Outgoing Address and Sender/Change/Return Address

Sending 10 Minima to the address:  MxYYUPDWVQKFOJQL3JGQKWIEMAVB3QTXLT

![TXInput](https://user-images.githubusercontent.com/60537663/121590097-cf973900-ca2f-11eb-8663-82080af3bf52.jpg)
![TXoutput1](https://user-images.githubusercontent.com/60537663/121590111-d1f99300-ca2f-11eb-9d04-c755d2ffc79d.jpg)
![TXoutput2](https://user-images.githubusercontent.com/60537663/121590123-d58d1a00-ca2f-11eb-85a8-93821f479db2.jpg)

Thanks,
Jazmin

**Comment by eurobuddha** [comment]
IMHO the fields in history should be completely unambiguous 

Senders address
Recipients address
Change address

currently Recipient is mis labelled, it is referring to the sender which is the opposite!!

**Comment by eliasnemr** [comment]
This is now changed in v1.1.4,

Input address is renamed to just Address.

Output address now recognises which address is *your* change address, and what address is going to the recipient/receiver

**Comment by jazminrib** [comment]
Tested and confirm the above - Change address is always my address and outgoing address is the counter party's address.
