### ISSUE TITLE
Terminal > Manually constructed txn with more inputs than outputs results in no change

### ISSUE THREAD

**Issue by jazminrib** [minima-global/Minima#277]
Hello, 

I may not be using the commands as intended, but an interesting outcome nonetheless. 

Issue Impact: Major
Device Manufacturer: Samsung
Device Model: S10
Device OS: Android
Device OS Version: 11
Application Version: apk: v0.98.24 wallet version 1.1.2

What Happened?: I manually constructed a transaction using the method Elias provided in the Telegram.
1. I used _coinsimple 0x00_ to find a coinID worth 25 Minima and used that as an input for the following transaction
2. created two outputs, one worth 5 Minima and one worth 10 Minima, sending both to the same address 
3. signed and sent the transaction. 
4. Recipient received the 15 but my balance was reduced by 25 i.e. no change was received

Terminal inputs: 
[TerminalManualTX.txt](https://github.com/minima-global/Minima/files/6640836/TerminalManualTX.txt)

What Did You Expect To Happen? I would receive 10 Minima in change

Steps to recreate: see terminal inputs

Logs
[ManualTxnLogs.txt](https://github.com/minima-global/Minima/files/6640861/ManualTxnLogs.txt)

My History:
![image](https://user-images.githubusercontent.com/60537663/121745859-d8097580-cafc-11eb-95c2-1c5569037f76.png)

Recipient's history:
![image](https://user-images.githubusercontent.com/60537663/121746106-43534780-cafd-11eb-9c6c-d6b0f937b03c.png)

Perhaps the change will return at some point?

Thanks,
Jazmin

**Comment by jazminrib** [comment]
Screen recording of transaction details:
https://user-images.githubusercontent.com/60537663/121747425-4fd89f80-caff-11eb-9355-6ec96bd40ff2.mp4

**Comment by eliasnemr** [comment]
You forgot to send the change back to yourself! 😬

**Comment by jazminrib** [comment]
Does that mean it's lost?

**Comment by eliasnemr** [comment]
Yes, you must explicitly calculate the change & your address for the third
output.

**Comment by jazminrib** [comment]
Oops, I assumed that would happen automatically

**Comment by spartacusrex99** [comment]
Those functions are as low level as they come..

You are fully in charge of the txn you create.

Raw power.

Great that you're playing with them!

**Comment by jazminrib** [comment]
Ah well now I know! Thanks both, appreciate the quick response. This can be closed.

**Comment by eurobuddha** [comment]
closing, great to see you digging so deep @jazminrib
