### ISSUE TITLE
Enhancement Wallet > History: Show contact name

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#282]
Hi again :)

Would be really nice if the recipient/outgoing addresses in the transaction details could be linked to our contacts.

![image](https://user-images.githubusercontent.com/60537663/121859338-7d843b00-ccef-11eb-996e-706a86d77dc1.png)

Thanks,
Jazmin

**Comment by glowkeeper** [comment]
Nice suggestion :)
