### ISSUE TITLE
Incentive Cash login - email address is case sensitive resulting in error "Your email doesn't match your previously used email"

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#283]
Hello, 

**Issue Impact:** Minor
**Device Manufacturer**: Samsung
**Device Model:** S10
**Device OS:** Android
**Device OS Version:** 11
**Application Version:** apk: v0.98.24 
**IC version** 1.0.43

**What Happened?:** In IC v1.0.42 I used to login with my email address in all lower case (this is saved in my phone and I was using the saved credentials to log in each time). 
Since upgrading to the new version, those saved credentials no longer work and I get an error that says **"Your email doesn't match your previously used email"**.
For some reason, now I can only login using Jaz.r@live.co.uk (capital J) and jaz.r@live.co.uk (all lower case) gives the error above. 

**What Did You Expect To Happen?:** I would be able to use previously saved credentials and email address would not be case sensitive.

**Steps to recreate:** Try to login with same email address but in different case.

**Screenshot 1:** Attempting to log in with my saved credentials on the phone
**Screenshot 2:** Error: "Your email doesn't match your previously used email"
**Screenshot 3:** After successful log in with Jaz.r@live.co.uk (Capital J) - shows email address in my Profile uses a capital

![SavedCredentials](https://user-images.githubusercontent.com/60537663/121879854-37d26d00-cd05-11eb-9ddc-592bcba8200c.jpg)

![WrongEmail](https://user-images.githubusercontent.com/60537663/121879999-66e8de80-cd05-11eb-86c0-a8ed739a2bda.jpg)

![image](https://user-images.githubusercontent.com/60537663/121880316-c47d2b00-cd05-11eb-8d8e-6447df230c73.png)

This can be a bit confusing and not perfect user experience, can we make the email address not case sensitive?

Thanks,
Jazmin

**Comment by eurobuddha** [comment]
email is always lowercase so you are correct, this should be case insensitive

**Comment by eliasnemr** [comment]
Now fixed in v1.0.44

**Comment by jazminrib** [comment]
Wow so speedy! Thanks guys.

**Comment by jazminrib** [comment]
Tested and confirm email is no long case sensitive. Thanks.
