### ISSUE TITLE
Minor issues with IC update 1.0.43

### ISSUE THREAD

**Issue by lewisc5** [minima-global/Minima#284]
Issue Impact: Minor
Device Manufacturer: Motorola
Device Model: Moto G Fast
Device OS: Android
Device OS Version: 11
Application Version: apk: v0.98.24
IC version 1.0.43

After starting up IC and going to other tabs, such as the wallet, when I come back a while later I'm seeing a "This site can't be reached" screen.

![Screenshot_20210614-120014](https://user-images.githubusercontent.com/85313270/121925385-db724c00-cd0a-11eb-919f-8d24b5bccd8c.png)

Also the "Rewards Pending" screen keeps trying to Fetch but never loads. I've rebooted a few times and reinstalled the dapp twice.

![Screenshot_20210614-121845](https://user-images.githubusercontent.com/85313270/121925543-08266380-cd0b-11eb-9494-413c120620bd.png)

**Comment by glowkeeper** [comment]
Hi @lewisc5 - I can see you received a reward - does the minidapp show that in your _Claimed Rewards_?

**Comment by lewisc5** [comment]
I received one yesterday but nothing new today

**Comment by glowkeeper** [comment]
We know what the issue is, and there's a fix for the next release of IC. Meanwhile, if you log out and log back in, you should get another set of tokens that will show up...

**Comment by lewisc5** [comment]
Thanks! Logging out and Logging in worked this time. :)

**Comment by glowkeeper** [comment]
Awesome :)
