### ISSUE TITLE
Wallet > Balance Flashing with Gimme 50 stuck in Mempool

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#285]
Hello,

Issue Impact: Minor
Device Manufacturer: Samsung
Device Model: S10
Device OS: Android
Device OS Version: 11
Application Version: apk: v0.98.24 Wallet v1.1.2

What Happened?: I thought I had Gimme50 running for the whole day via Power Console but when I checked it, the Balance was constantly flashing and 50 was stuck in the Mempool. The last tx went through at 12:43. It's possible my laptop went to sleep after 12:43 which might have caused the Power console to stop running but the Gimme50 should still have gone through.
I stopped and started the Power Console again at 5:15 and it restarted successfully and the next Gimme50 seemed to go through fine... 

What Did You Expect To Happen?: Gimme 50 to not get stuck.

Steps to recreate: Not sure sorry, hopefully the logs will help.
Logs: 
[Gimme50Stuck.txt](https://github.com/minima-global/Minima/files/6649707/Gimme50Stuck.txt)
Logs from after restarting Power console gimme50 at 5:15
[Gimme50Stuck2.txt](https://github.com/minima-global/Minima/files/6649887/Gimme50Stuck2.txt)

Screenshot 1: Final state - shows how the Balance page is stuck 
Screenshot 2: Shows 5:15pm Gimme 50 going through fine with 50 still stuck in mempool
Screenshot 3 : Final State -History page

![MempoolStuck](https://user-images.githubusercontent.com/60537663/121927950-8dc00880-cd37-11eb-8441-466ee9b46300.jpg)

![Screenshot_20210614-171543_Brave](https://user-images.githubusercontent.com/60537663/121925895-489ad700-cd35-11eb-8a29-69779bbe2847.jpg)
![Gimme50Stuck](https://user-images.githubusercontent.com/60537663/121927960-90baf900-cd37-11eb-83b0-886db0d64e99.jpg)

Thanks
Jazmin

**Comment by jazminrib** [comment]
Flushmempool -hard removed this. But what would be the root cause? Surely users won't be expected to have to run flushmempool? 

![image](https://user-images.githubusercontent.com/60537663/121929365-0b384880-cd39-11eb-9c73-b1f163c0e122.png)

**Comment by glowkeeper** [comment]
Thanks @jazminrib - we'll investigate...
