### ISSUE TITLE
How to control light/dark mode? 

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#287]
Hello,

Issue Impact: Minor
Device Manufacturer: Samsung
Device Model: S10
Device OS: Android
Device OS Version: 11
Application Version: apk: v0.98.24
Wallet version 1.1.2

How do we control light/dark mode now? 

Should it be from the system default? My phone is in light mode but my wallet is in dark mode.
And it doesn't seem to change if I change my phone settings. 

Perhaps this setting can be chosen from the hub rather than in individual apps? 

![Screenshot_20210615-173143_Settings.jpg](https://user-images.githubusercontent.com/60537663/122090967-3c2f8080-ce00-11eb-814f-5f17af993fda.jpg)

![Screenshot_20210615-173416_Brave.jpg](https://user-images.githubusercontent.com/60537663/122091127-61bc8a00-ce00-11eb-9e0e-ee02dd4118ea.jpg)

Thanks
Jazmin

**Comment by eliasnemr** [comment]
It is according to your system setting.. is it not working for your phone?

**Comment by jazminrib** [comment]
It doesn't appear to be working, I also tried removing the Theme that I was using on my phone but even using the Default Display settings doesn't seem to impact the light/dark mode in the app. Bob also confirmed the same.
I closed the app and reopened, also rebooted my phone but no change...

**Comment by eliasnemr** [comment]
Okay, I'll have a look at it

**Comment by eliasnemr** [comment]
Hi Jazmin, brave browser has its own lightMode/darkMode & default system setting.  If you set any of the 3 it will manually override the systems setting.

**Comment by jazminrib** [comment]
Hi Elias, ah yes that's what happening, I was using dark mode in Brave. 

Tested all 3 options and the mode in the app changes as expected. Thanks for looking into that.
