### ISSUE TITLE
Enhancements to backup process

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#288]
Hello,

I think the backup process needs to be a bit more user friendly.
When I select backup, a pop up appears and disappears. At this stage I thought the backup was complete so was navigating away from the screen, not knowing that I needed to wait for another pop up in order to select where to save the back up. 
If you navigate away from the screen you don't get the second pop up to choose where to save the backup and I didn't realise the process wasn't finished. 

Could we add some more information for the users? E.g.
Backup starting...
Backup in progress, do not leave this screen...
Choose where to save your backup...

Recording1 shows the process
Recording2 shows what happens when you navigate away from the page. The second notification eventually comes but with no prompt for where to save the file.

https://user-images.githubusercontent.com/60537663/122099048-79e4d700-ce09-11eb-9b1c-75f8ba370970.mp4

https://user-images.githubusercontent.com/60537663/122099068-7ea98b00-ce09-11eb-9c20-295f82354170.mp4

Is it also possible to password protect/encrypt the backups somehow so that if someone else got hold of it they couldn't restore it? 

Thanks!
Jazmin

**Comment by jazminrib** [comment]
Sorry phone details:

Issue Impact: Minor
Device Manufacturer: Samsung
Device Model: S10
Device OS: Android
Device OS Version: 11
Application Version: apk: v0.98.24
Wallet version 1.1.2

Also my phone doesn't give me any option to save the backup locally to my phone which is a shame, but I guess this is to do with the phone and not Minima.
