### ISSUE TITLE
Storefront hangs loading after upload attempt

### ISSUE THREAD

**Issue by jazminrib** [minima-global/Minima#289]
Hello,

Issue Impact: Minor
Device Manufacturer: Samsung
Device Model: S10
Device OS: Android
Device OS Version: 11
Application Version: apk: v0.98.24
Storefront version 1.0.3

What Happened?: I used the + to see what happens when trying to import something to the storefront. I selected a minidapp I previously downloaded (I didn't really expect it to import as I don't think this is what the + function is for).
It appeared to be loading but nothing imported, then I clicked on the + again but Return to the storefront without selecting anything and the storefront hangs on the loading page. I have to close the storefront and reopen for it to work again.

What Did You Expect To Happen?: Storefront would return to normal functionality

Steps to recreate:
1.Click the + from storefront
2. Select a file (appears to load but doesn't import - ok)
3. Click the + again
4. Click back without selecting anything 
5. Storefront hangs on loading screen 

https://user-images.githubusercontent.com/60537663/122181909-afc5a200-ce81-11eb-9ee6-22017fd95837.mp4

Question: what type of files can be uploaded with this + function? Is this specified somewhere?

Thanks,
Jazmin

**Comment by glowkeeper** [comment]
To answer the question - the + sign is for loading new (decentralised) stores. 

Meanwhile - thanks for the detailed description - I'll drop in a fix in due course...
