### ISSUE TITLE
Incentive Cash FAQ says "You will earn 1 Minima a week"

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#290]
Hi, 

The new version of IC 1.0.43 says you will earn 1 Minima per week...

![image](https://user-images.githubusercontent.com/60537663/122256223-c17d6880-cec6-11eb-9a98-87fa0ffa98cb.png)

Thanks
Jazmin

**Comment by eurobuddha** [comment]
this will be corrected, good catch

**Comment by eliasnemr** [comment]
This is now fixed in iC v2.0.0.. coming soon ;)

**Comment by jazminrib** [comment]
Checked and confirm this is now fixed. 

The other added info in the FAQs is a good improvement too 🙂
