### ISSUE TITLE
Storefront help and email links

### ISSUE THREAD

**Issue by hmgovt** [minima-global/Minima#291]
Links to Github minidapp and storefront pages, technical problem and general enquiries email addresses should be added. Each is unlinked at present.

![Screenshot_20210610-145817_Chrome](https://user-images.githubusercontent.com/85314004/122263618-8e3ed780-cece-11eb-97ff-b43ca0305ae5.jpg)
![Screenshot_20210610-145750_Chrome](https://user-images.githubusercontent.com/85314004/122263623-90089b00-cece-11eb-80d9-d326b8316926.jpg)

**Comment by eurobuddha** [comment]
Yes agreed those links and email should definitely be clickable html, not just text

**Comment by glowkeeper** [comment]
@eurobuddha - cool - agreed. And does the community team want to give that text a once over, too?

**Comment by eurobuddha** [comment]
Will do, good idea

Sent from Mail for Windows 10
