### ISSUE TITLE
Terminal > Txnvalidate message errors 

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#294]
Hello,

I have created 4 transactions via the terminal transaction IDs: 1, 123, 234, 345. 
I used txnlist to show them all and then I tried to run txnvalidate against each of them. 

3 of them return with errors in the message only one returns with a full output - is this expected behaviour? 

The one that returns the full output is actually an invalid transaction (tx 345). Of the others, 2 have inputs > outputs and the other is empty. 

Maybe I am too out of my depth here, I guess I expected a full output for all of them rather than seeing the errors in the messages.

[TxnValidateErrors.txt](https://github.com/minima-global/Minima/files/6671421/TxnValidateErrors.txt)

Thanks as always,
Jazmin

**Comment by jazminrib** [comment]
Think I answered my own question. Txs 123 and 234 have been sent so I guess the coin ids used as inputs are no longer valid. I added an input and output to tx1 and that's validating fully now. 

Sorry, think I'll stay out of the terminal for now!
