### ISSUE TITLE
Enhancement: Warning when creating a contact with a duplicate name

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#295]
Hi, 

Is it possible to add a warning if someone tries to create a contact with a name that already exists? 

![image](https://user-images.githubusercontent.com/60537663/122431350-48e0df80-cf8c-11eb-856f-814a185e2090.png)

Thanks
Jazmin

**Comment by Sw1fty** [comment]
This is still an issue.
Also you can create a contact using your own address
