### ISSUE TITLE
Wallet > Token Creation - Inconsistent Max Amount Validation Errors

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#296]
Hello, 

Issue Impact: Minor
Apk: v0.98.24
Wallet: v1.1.2

Minor issue with inconsistent max amount validation errors.

**What Happened?**
Attempting to input between up to 19 zeroes results in "1000000000000 MAX..." error but attempting to input 20 zeroes results in java error.
Beyond 20 zeroes, the red validation text shows (no issues here)

**What Did You Expect To Happen?**
Error message for 20 zeroes would show the MAX error instead of Java error. 

**Steps to recreate:**
1. Input 1+19 zeroes - try to create the token - Max error (screenshot 1)
2. Input 1+20 zeroes - try to create the token - Java error (screenshot 2)

![image](https://user-images.githubusercontent.com/60537663/122575658-e39ef400-d048-11eb-86f7-5e88d72d64ae.png)

![image](https://user-images.githubusercontent.com/60537663/122575690-e994d500-d048-11eb-8811-4b70da5dfe82.png)

Thanks
Jazmin

**Comment by Sw1fty** [comment]
@eliasnemr Has the form validation been updated?
