### ISSUE TITLE
Incentive cash - discrepancy between confirmed amount in Wallet Balance and Total in IC

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#300]
Hello, 

Issue Impact: Minor
Device Manufacturer: Samsung
Device Model: S10
Device OS: Android
Device OS Version: 11
Application Version: apk: v0.98.24 Wallet v1.1.2

I have a discrepancy between the confirmed amount balance of Incentive cash in my wallet (42) vs the total collected + pending rewards in the IC app (31) ... I believe all of us in the testing group have this.
The latest rewards were issued this morning - prior to the collection my confirmed wallet balance for IC was 49, so appears the confirmed amount decreased by 7 after the latest collection... 

before collection (49)
![image](https://user-images.githubusercontent.com/60537663/122744904-61991000-d280-11eb-9e43-437cc6b7a906.png)
after collection (42)
![image](https://user-images.githubusercontent.com/60537663/122742508-ec2c4000-d27d-11eb-89e4-7f9b75356619.png)

After collection (total 31)
![image](https://user-images.githubusercontent.com/60537663/122742582-00703d00-d27e-11eb-80bb-4e2f5fada381.png)
![image](https://user-images.githubusercontent.com/60537663/122742596-049c5a80-d27e-11eb-98f6-33bc2214743b.png)

Logs:
[ICLogs.txt](https://github.com/minima-global/Minima/files/6685750/ICLogs.txt)

Thanks
Jazmin

**Comment by eurobuddha** [comment]
@eliasnemr and @glowkeeper will investigate/explain asap. thank you

**Comment by eliasnemr** [comment]
A decrease makes sense as when you collect, the transaction posts away some iC to another address

**Comment by Sw1fty** [comment]
@glowkeeper @eliasnemr Can we close this issue?

**Comment by glowkeeper** [comment]
absolutely
