### ISSUE TITLE
IncentiveCash website registration

### ISSUE THREAD

**Issue by eliasnemr** [minima-global/Minima#302]
Hi, once you reach your max referral you get the error as intended, but if you try to register again (if your max referral is reset) the messages are stacked as in the image below..

<img width="987" alt="Screenshot 2021-06-21 at 5 12 35 PM" src="https://user-images.githubusercontent.com/33732313/122776556-e0f40700-d2b3-11eb-8865-49aaa0522486.png">

**Comment by glowkeeper** [comment]
I'm struggling to recreate this - can you remember how you got this?

**Comment by Sw1fty** [comment]
@glowkeeper where you able to recreate? If not probably worth closing this issue down now

**Comment by glowkeeper** [comment]
Unable to recreate - please close
