### ISSUE TITLE
Enhancement: Wallet > Token URL warning for invalid characters 

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#310]
Hiya,

Wallet v 1.1.4

The warning message for the token icon URL does not say which characters are not supported. It rejects this URL unless I remove the @ symbol.

If there are several invalid characters, maybe worth including which characters are invalid in the warning message?

![image](https://user-images.githubusercontent.com/60537663/123558007-ebb70c00-d78b-11eb-84c8-ced908075ee0.png)

Thanks
Jazmin

**Comment by Sw1fty** [comment]
@eliasnemr Did we update this to auto html encode the urls?
