### ISSUE TITLE
Wallet >Send page: Address cut off

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#311]
Hello, 

Issue Impact: Minor
Device Manufacturer: Samsung
Device Model: S10
Device OS: Android
Device OS Version: 11
Application Version: apk: v0.98.24 Wallet v1.1.4

The Address field cuts off the last few characters. Ideally the whole address should be visible.

![image](https://user-images.githubusercontent.com/60537663/123627698-38412c80-d80a-11eb-8927-78c5d2687227.png)

Thanks
Jazmin

**Comment by eliasnemr** [comment]
Now fixed in wallet v1.1.5

**Comment by eurobuddha** [comment]
confirmed fixed by @MiniJaz
