### ISSUE TITLE
Wallet: Gimme50 makes landscape view very restrictive

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#312]
Hi,

Issue Impact: Minor
Device Manufacturer: Samsung
Device Model: S10
Device OS: Android
Device OS Version: 11
Application Version: apk: v0.98.24 Wallet v1.1.4

Having the Gimme50 pinned to the bottom of the page makes landscape view very hard to use. Can Gimme50 move with the rest of the page? 

https://user-images.githubusercontent.com/60537663/123628563-257b2780-d80b-11eb-84be-556a0c79638e.mp4

Thanks,
Jazmin

**Comment by eurobuddha** [comment]
confirmed as fixed by @MiniJaz
