### ISSUE TITLE
Wallet > Delete Contact: contact details pop up appears

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#313]
Hi

Issue Impact: Minor
Device Manufacturer: Samsung
Device Model: S10
Device OS: Android
Device OS Version: 11
Application Version: apk: v0.98.24 Wallet v1.1.4

When trying to delete a contact, the contact details page pops up in front of the "are you sure you want to delete" message.

https://user-images.githubusercontent.com/60537663/123629056-b8b45d00-d80b-11eb-8457-70cb59829981.mp4

Expected behaviour would be for only the delete warning message to appear and not the contact details page.

Thanks
Jazmin

**Comment by eliasnemr** [comment]
Now fixed in Wallet v1.1.5.

![Screenshot 2021-06-30 at 11 23 48 AM](https://user-images.githubusercontent.com/33732313/123927686-c39af900-d995-11eb-981f-b33f8c0671f0.png)

**Comment by eurobuddha** [comment]
confirmed fixed by @MiniJaz
