### ISSUE TITLE
Enhancement: Gimme 50 only on Balance screen

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#314]
Hello, 

Wallet v1.1.4

I don't think it's necessary to have the Gimme 50 option on every page in the wallet. Just the Balance page would be most appropriate in my opinion. It interferes with the user experience on the send and create token screens by cutting off the Send Funds and Create Token buttons.

![Screenshot_20210628-122924_Brave](https://user-images.githubusercontent.com/60537663/123629789-9bcc5980-d80c-11eb-832f-840076107c49.jpg)
![Screenshot_20210628-122932_Brave](https://user-images.githubusercontent.com/60537663/123629803-9e2eb380-d80c-11eb-9ee9-6c906b09550b.jpg)

Thanks
Jazmin

**Comment by eliasnemr** [comment]
I agree, I'll discuss this with our UI designer.  

Thanks

**Comment by eurobuddha** [comment]
confirmed as fixed by @MiniJaz
