### ISSUE TITLE
Wallet > Contacts: After deleting a contact, remaining contacts are no longer in alphabetical order

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#321]
Hello,

Issue Impact: Minor
Device Manufacturer: Samsung
Device Model: S10
Device OS: Android
Device OS Version: 11
Application Version: apk: v0.98.29 
Wallet: 1.1.4

What Happened: After deleting a contact the contacts no longer show in alphabetical order. See video below. 

Expected result: Contacts remain in alphabetical order. 

Issue does fix itself after a page refresh. 

Video shows contacts in order before deleting a contact and out of order after deleting a contact.
https://user-images.githubusercontent.com/60537663/124395153-6b982580-dcfa-11eb-9f36-f17fbcc712d2.mp4

Thanks
Jazmin

**Comment by eliasnemr** [comment]
Now fixed in v1.1.5

**Comment by eurobuddha** [comment]
confirmed as fixed by @MiniJaz
