### ISSUE TITLE
Contacts Search function: contact does not appear after correcting a typo

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#322]
Hi,

Issue Impact: Minor
Device Manufacturer: Samsung
Device Model: S10
Device OS: Android
Device OS Version: 11
Application Version: apk: v0.98.29 
Wallet: 1.1.4

What happened: From both the Send page and the Contacts page. When searching for a contact, if you make a typo and then correct it, the contact does not appear. You have to clear the box completely and start again. 

Expected result: The search is regenerated after typo.

https://user-images.githubusercontent.com/60537663/124395351-93d45400-dcfb-11eb-94e3-ab06e79b1d8d.mp4

Thanks
Jazmin

**Comment by eliasnemr** [comment]
Now fixed in v1.1.5

**Comment by eurobuddha** [comment]
confirmed as fixed by @MiniJaz
