### ISSUE TITLE
Change address in Transaction Details is not correct for recipient

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#323]
Hi Elias,

Issue Impact: Minor
Device Manufacturer: Samsung
Device Model: S10
Device OS: Android
Device OS Version: 11
Application Version: apk: v0.98.29
Wallet: 1.1.4

I know this was changed recently so that the Change Address is always the users address, however looking at the sender and receiver's transaction details side by side, having Change Address being the incoming amount on the right side of the screenshot doesn't look correct. 

Maybe _Change Address_ can just be renamed to _My Address_? Then I think both sides would make sense...

Screenshot shows Sender's tx details on the left , recipient's on the right:

![](https://cdn.discordapp.com/attachments/813882550204235826/861521432421072926/unknown.png)

Thanks
Jazmin

**Comment by eliasnemr** [comment]
Good idea, now changed in wallet v1.1.5

**Comment by eurobuddha** [comment]
confirmed as fixed by @MiniJaz
