### ISSUE TITLE
Block shows multiple entries of same block during consolidation

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#326]
Hi 

Issue Impact: Minor
Device Manufacturer: Samsung
Device Model: S10
Device OS: Android
Device OS Version: 11
Application Version: apk: v0.98.29
Block: 1.0.9

What happened: 
In Block, multiple entries of the same block were showing. If I went to other pages in Block explorer they were all duplicates of the same block. 
When I checked the logs, it seemed like the consolidation was running (I have Consolidate turned on via terminal) 

![Screenshot_20210705-221702_Brave.jpg](https://user-images.githubusercontent.com/60537663/124613176-de281300-de6a-11eb-993d-ce3ab31d2b65.jpg)

![Screenshot_20210705-221718_Minima.jpg](https://user-images.githubusercontent.com/60537663/124613196-e2ecc700-de6a-11eb-8357-865ce53b0ac5.jpg)

When this activity in the logs isn't happening, block appears to be working fine.

Let me know if you need any more information.

Thanks
Jazmin

**Comment by eliasnemr** [comment]
Hi Jazmin, we are aware of this issue and is being worked on,

Thanks

**Comment by eliasnemr** [comment]
Hi Jazmin, we are aware of this issue and is being worked on,

Thanks

**Comment by eliasnemr** [comment]
Now fixed in Block v1.0.13
