### ISSUE TITLE
"No Minidapps installed yet" message after installing a new dapp.

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#327]
Issue Impact: Minor
Device Manufacturer: Samsung
Device Model: S10
Device OS: Android
Device OS Version: 11
Application Version: apk: v0.98.30

Hello,

Quite often when I install a new app, I see this page.
It just needs a page refresh to get rid of the message but hopefully it's an easy thing to fix.

![Screenshot_20210709-172606_Brave.jpg](https://user-images.githubusercontent.com/60537663/125109993-f81c5c80-e0db-11eb-9116-6ff25bd5abbc.jpg)

I couldn't get any detail from the logs at the time as it just showed this:
![Screenshot_20210709-173940_Minima.jpg](https://user-images.githubusercontent.com/60537663/125110676-cbb51000-e0dc-11eb-8df4-fde14c41e823.jpg)

Let me know if you need them and will try again.

Thanks,
Jaz

**Comment by eurobuddha** [comment]
I have had this bug before, it clears when you refresh the browser in my experience. Still nice catch

**Comment by eliasnemr** [comment]
Hi, can I know what version of block you have installed? It seems like you're being spammed with 'adding txpow' messages which isn't the case with the latest v1.0.14

**Comment by MiniJaz** [comment]
Hi Elias, 

Ah thanks, I had v1.0.9 and v1.0.11 installed. I've removed them both now and installed v1.0.14. 

Is this also connected to the "No Minidapps installed yet" message?

**Comment by eliasnemr** [comment]
Cool.

No this is a MiniDAPP hub issue
