### ISSUE TITLE
Block: Search bar UI bug

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#329]
Logging on behalf of discord user herman_radin#0710.

Minor issue
Samsung Galaxy S10 (Snapdragon)
Android 11
Apk v.0.98.30
Block v1.0.14 

Once you open the Block app, there is a search bar in the center of the page. There is  a minor UI bug since the magnifier displays incorrectly overlaying the placeholder text.

User says browser zoom setting are set as default. 

![SmartSelect_20210711-093118_Samsung_Internet.jpg](https://user-images.githubusercontent.com/60537663/125196795-0b9e0380-e253-11eb-85db-3d9b4bd05031.jpg)

Thanks,
Jazmin

**Comment by eliasnemr** [comment]
Fixed in v1.0.15
