### ISSUE TITLE
Block: returns to top of page 1 when new block comes in

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#334]
Issue Impact: Minor
Device Manufacturer: Samsung
Device Model: S10
Device OS: Android
Device OS Version: 11
Application Version: apk: v0.98.30
Block v 1.0.14

Hello,

When using Block, whenever a new block comes in, the user is returned to top of page 1 which is a bit annoying.

Expected behaviour would be for the page to remain where it is even as new blocks come in. 

Recording below showing
1. being automatically returned to page 1 from page 4 and
2. from bottom of page 1 back to the top when new blocks appear. 

Thanks
Jazmin

https://user-images.githubusercontent.com/60537663/125479726-9ef36f66-9012-4210-9d9e-67f1b856c5ee.mp4

**Comment by eliasnemr** [comment]
Now fixed on Block 1.0.17.
