### ISSUE TITLE
Block: TxPoW ID, Parent, Coin ID, Token ID are cut off

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#335]
Issue Impact: Minor
Device Manufacturer: Samsung
Device Model: S10
Device OS: Android
Device OS Version: 11
Application Version: apk: v0.98.30
Block v 1.0.14

Hello, 

When looking into a block details, the TxPoW ID, Parent, Coin ID, Token ID are cut off. 

This is the case in landscape mode too. Recording below.

https://user-images.githubusercontent.com/60537663/125480981-76f4eeaa-6b1e-4af7-befb-41a437eacfea.mp4

Thanks
Jazmin

**Comment by eliasnemr** [comment]
This is what's been decided in our design, you can still copy to clipboard and use if necessary
