### ISSUE TITLE
Block: SQL and Java Errors in logs

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#336]
Issue Impact: Minor
Device Manufacturer: Samsung
Device Model: S10
Device OS: Android
Device OS Version: 11
Application Version: apk: v0.98.30
Block v 1.0.14

Hello, 

I believe the attached log errors are from the Block app. There does not seem to be any issues with the app itself but these errors are consistently appearing in the logs. 

[SQL Java Errors.txt](https://github.com/minima-global/Minima/files/6810075/SQL.Java.Errors.txt)

Thanks,
Jazmin

**Comment by eliasnemr** [comment]
Hi Jazmin, this has already been resolved on Block v1.0.15, please install the latest version.  Thank you

**Comment by MiniJaz** [comment]
Ah I didn't realise the storefront was being constantly updated! Thanks will get the latest version.

**Comment by MiniJaz** [comment]
Hiya, 

Sorry I uninstalled Block v1.0.14 last night and installed v1.0.15 but I am still seeing these messages this morning:
[SQL Java Errors 2.txt](https://github.com/minima-global/Minima/files/6814567/SQL.Java.Errors.2.txt)

Thanks
Jazmin

**Comment by eliasnemr** [comment]
Hi Jazmin, 

Sorry, please uninstall v1.0.15 until further notice - there is an issue with block & the apk's native H2 DB in comparison to MySql that was tested locally.. so it's currently totally broken.  New version in the next coming days.

Thank you

**Comment by eliasnemr** [comment]
That's fixed in the latest version released 2 weeks ago.

**Comment by eliasnemr** [comment]
Now checks for a transaction bigger than 16k (H2 DB max col size).

Implemented in Block v 1.0.18
