### ISSUE TITLE
Enhancement: Ability to copy token description

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#341]
Hi,

Device Manufacturer: Samsung
Device Model: S10
Device OS: Android
Device OS Version: 11
Application Version: apk: v0.98.30
Wallet: v1.1.5

Hi,

Is it possible to add functionality to copy text from the token description? 
For example it's not possible to copy the url in this token description:

![Screenshot_20210715-212620_Brave.jpg](https://user-images.githubusercontent.com/60537663/125852948-590aa22a-150d-4475-a5c7-b64af0d36275.jpg)

Thanks
Jazmin

**Comment by eurobuddha** [comment]
good idea, add functionality to the token. maybe even a clickable link!

**Comment by eliasnemr** [comment]
Fixed in v1.1.6.. now able to copy description
