### ISSUE TITLE
Bypass Incentive form referral limitation

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#343]
Raised on behalf of Haslev, discord user #9710

Device Manufacturer: Any
Device Model: Any
OS: Any
OS Version: Any

What Happened?

- There is a way to register into Incentive program without referral limitation

What Did You Expect To Happen?

-  Referral link to be limited by max number of referrals

Step by step, from the point of opening the app / miniDapp, what did you do to encounter/trigger the issue?

-  User was able to use Devtools, inspect web requests and intercept the web request, changing the max limit of users. 

Videos below 
1. on Mac using Local Overrides

https://user-images.githubusercontent.com/60537663/126385729-3d7a75f8-69f6-4417-98bd-a42ba3f90dea.mp4

2. In Chrome using TamperDev extension

https://user-images.githubusercontent.com/60537663/126385754-cfaf642c-3a6f-46c2-b02c-611f6848ea0b.mp4

**Comment by glowkeeper** [comment]
Nice! I've been chatting to Haslev about this - there are a few more steps to get through before we properly register a user, so we may still prevent them bypassing _max_ further down the line...I'll give it all a thorough check.

**Comment by glowkeeper** [comment]
I haven't _quite_ fixed this, BUT I have made improvements:

1. To bypass the WHOLE registration workflow and register even _if_ the referrer has reached their max is now much harder
2. There's an extra check, too
3. Furthermore, the checks are more efficient
4. We know how to fix it definitively and that will be done in due course...

**Comment by glowkeeper** [comment]
It's now impossible to bypass the referral limitation as I've added a check server-side, too.
