### ISSUE TITLE
Wallet > Send: Contact search bug (Same as #322)

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#351]
Issue Impact: Minor
Device Manufacturer: Samsung
Device Model: S10
Device OS: Android
Device OS Version: 11
Application Version: apk: v0.98.32
Wallet: 1.1.5

Hiya, 

Please refer to issue #322 for details. The issue was fixed on the Contacts page but still exists on the Send page when searching for a contact. 

Thanks
Jazmin

**Comment by eliasnemr** [comment]
Fixed in v1.1.8
