### ISSUE TITLE
Minihub enhancement: Notification icon when a new version of minidapp is available

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#356]
Hello, 

Not sure if this is possible but a nice to have for the long run would be to have a notification icon against installed apps in the minihub to indicate when new versions of your minidapps are available in the storefront e.g. when a new wallet version comes out. 

Thanks,
Jazmin

**Comment by stevie101** [comment]
Thanks @MiniJaz noted and we'll look into it. Thanks for the suggestion!
