### ISSUE TITLE
Enhancement: Option to force a resync from launch page/terminal

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#357]
Hello, 

Maybe this isn't something that would be required in mainnet, but in the case of ending up on the wrong chain, it would be good to be able to force a resync from the launch page and/or via terminal command, effectively doing whatever happens when the phone is rebooted and a synchronisation to the latest block occurs. 

If this is just testnet issues then feel free to ignore!

Thanks
Jazmin

**Comment by spartacusrex99** [comment]
Absolutely.

This is in the road map.

It should only require a seed phrase and an archive node.. for a full
resync from genesis..

OR.. if you have moved your coins in last 3 months should be possible from
any user to any user.

:)

**Comment by MiniJaz** [comment]
Good to know, thank you!

Interested to learn how the archive nodes will work and who will run them, maybe a question for the next Dev call? :)
