### ISSUE TITLE
98.39 crash on Huawei. Won't start up. 

### ISSUE THREAD

**Issue by rafaroberto** [minima-global/Minima#361]
Screen recoding of manual restart following a crash on Huawei P20Pro. 
Can't copy logs. 

https://user-images.githubusercontent.com/85311500/128425663-61876962-8e88-4e22-ae96-68ba31ec6e50.mp4

https://user-images.githubusercontent.com/85311500/128425691-e6e61d18-d4a2-4c12-8940-5199102ff7d0.mp4

**Comment by stevie101** [comment]
Hi @rafaroberto thanks for raising this issue, it's one that we're aware of, and will address in an up and coming build. Many thanks.

**Comment by Sw1fty** [comment]
Hi @rafaroberto,

As we're a few versions on now I'm going to close this issue.
If its still a problem drop a comment and I'll reopen

Thanks for taking the time to report this issue.
