### ISSUE TITLE
Hash rate showing 0 in Status command

### ISSUE THREAD

**Issue by Jazminima** [minima-global/Minima#557]
In the app version 100.31, from time to time, the hash rate shows 0.0 when running the status command.

Also seems to happen on Windows from time to time.

**Comment by MiniJaz** [comment]
![Screenshot_20220318-164039_Minima.jpg](https://user-images.githubusercontent.com/60537663/159045819-59556cbf-36a2-40ae-a049-6297604a7f36.jpg)
