### ISSUE TITLE
This prompt appears when you run the program under windows. How to solve it?

### ISSUE THREAD

**Issue by Ambassador-pi** [minima-global/Minima#566]
Minima @ 22/04/2022 15:51:44 [5.2 MB] : ****************************************
******
Minima @ 22/04/2022 15:51:44 [5.9 MB] : *  __  __  ____  _  _  ____  __  __    _
_    *
Minima @ 22/04/2022 15:51:44 [5.9 MB] : * (  \/  )(_  _)( \( )(_  _)(  \/  )  /_
_\   *
Minima @ 22/04/2022 15:51:44 [5.9 MB] : *  )    (  _)(_  )  (  _)(_  )    (  /(_
_)\  *
Minima @ 22/04/2022 15:51:44 [5.9 MB] : * (_/\/\_)(____)(_)\_)(____)(_/\/\_)(__)
(__) *
Minima @ 22/04/2022 15:51:44 [5.9 MB] : *
     *
Minima @ 22/04/2022 15:51:44 [5.9 MB] : ****************************************
******
Minima @ 22/04/2022 15:51:44 [5.9 MB] : Welcome to Minima v0.100.32 - for assist
ance type help. Then press enter.
Minima @ 22/04/2022 15:51:46 [30.4 MB] : Load Object file does not exist : C:\Us
ers\Administrator\.minima\databases\userprefs.db
Minima @ 22/04/2022 15:51:46 [30.4 MB] : Load Object file does not exist : C:\Us
ers\Administrator\.minima\databases\cascade.db
Minima @ 22/04/2022 15:51:46 [30.4 MB] : Load Object file does not exist : C:\Us
ers\Administrator\.minima\databases\chaintree.db
Minima @ 22/04/2022 15:51:46 [30.4 MB] : Load Object file does not exist : C:\Us
ers\Administrator\.minima\databases\p2p.db
Minima @ 22/04/2022 15:51:46 [9.3 MB] : RPC Server started on port : 9002
Minima @ 22/04/2022 15:51:46 [15.4 MB] : [+] P2P Version: 1.0
Minima @ 22/04/2022 15:51:46 [15.4 MB] : [+] Doing discovery connection with def
ault node: /34.95.47.143:9001
Minima @ 22/04/2022 15:51:49 [45.5 MB] : [+] Connected to the blockchain Initial
 Block Download received. size:2.0 MB blocks:1029
Minima @ 22/04/2022 15:51:56 [68.5 MB] : [-] WARNING : No Known peers ( -clean +
 delay )
Minima @ 22/04/2022 15:51:56 [68.5 MB] : [+] Doing discovery connection with def
ault node: /34.130.196.123:9001
Minima @ 22/04/2022 15:51:58 [69.2 MB] : [+] Connected to the blockchain Initial
 Block Download received. size:5 bytes blocks:0
Minima @ 22/04/2022 15:52:09 [70.3 MB] : [-] WARNING : Failed to set my ip. Secr
ets do not match - could be a delay. MySecret: 0x91FBDC2C28F6A1039C8B3691 Receiv
ed secret: 0xBB9B4D4377D534CC3AD7AF91
Minima @ 22/04/2022 15:52:09 [70.3 MB] : [+] Setting My IP: 198.245.60.73
Minima @ 22/04/2022 15:52:09 [71.5 MB] : [+] Connected to the blockchain Initial
 Block Download received. size:1.2 KB blocks:1
Minima @ 22/04/2022 15:52:21 [72.9 MB] : [+] Connected to the blockchain Initial
 Block Download received. size:5 bytes blocks:0
Minima @ 22/04/2022 15:52:32 [74.1 MB] : [+] Connected to the blockchain Initial
 Block Download received. size:5 bytes blocks:0
Minima @ 22/04/2022 15:52:45 [85.5 MB] : [+] Connected to the blockchain Initial
 Block Download received. size:5 bytes blocks:0
Minima @ 22/04/2022 15:52:58 [31.5 MB] : No Archive blocks found to match New Us
er..
Minima @ 22/04/2022 15:53:03 [32.4 MB] : [+] Connected to the blockchain Initial
 Block Download received. size:5 bytes blocks:0
Minima @ 22/04/2022 15:53:08 [35.5 MB] : [-] Too many outgoing connections, disc
onnecting

**Comment by ycsx** [comment]
Too many outgoing connections, disconnecting me too
