### ISSUE TITLE
Minima coins stuck in mempool

### ISSUE THREAD

**Issue by eliasnemr** [minima-global/Minima#98]
My tokens are stuck in the mempool after creating a token, and also sending some tokens out to random addresses.

Here's a screenshot:
![Screenshot_20210216-155109_Chrome](https://user-images.githubusercontent.com/33732313/108071965-04414800-706f-11eb-9832-1711ccefc91b.jpg)

`Minima @ 16/02/2021 15:22:37 [3.1 MB] : Service : onCreate
Minima @ 16/02/2021 15:22:37 [3.3 MB] : **********************************************
Minima @ 16/02/2021 15:22:37 [3.3 MB] : *  __  __  ____  _  _  ____  __  __    __    *
Minima @ 16/02/2021 15:22:37 [3.3 MB] : * (  \/  )(_  _)( \( )(_  _)(  \/  )  /__\   *
Minima @ 16/02/2021 15:22:37 [3.3 MB] : *  )    (  _)(_  )  (  _)(_  )    (  /(__)\  *
Minima @ 16/02/2021 15:22:37 [3.3 MB] : * (_/\/\_)(____)(_)\_)(____)(_/\/\_)(__)(__) *
Minima @ 16/02/2021 15:22:37 [3.3 MB] : *                                            *
Minima @ 16/02/2021 15:22:37 [3.3 MB] : **********************************************
Minima @ 16/02/2021 15:22:37 [3.3 MB] : Welcome to Minima. For assistance type help. Then press enter.
Minima @ 16/02/2021 15:22:37 [3.3 MB] : Minima files : /data/user/0/global.org.minima/files
Minima @ 16/02/2021 15:22:37 [3.3 MB] : Minima version 0.97.12
Minima @ 16/02/2021 15:22:37 [3.3 MB] : Daemon Started..
Minima @ 16/02/2021 15:22:37 [3.4 MB] : Service : Initialise begin..
Minima @ 16/02/2021 15:22:38 [4.2 MB] : CONNECTED TO SERVICE
Minima @ 16/02/2021 15:22:38 [4.3 MB] : ACTIVITY : LISTENING FOR SYNC COMPLETE..
Minima @ 16/02/2021 15:22:49 [2.4 MB] : Loading DB.. please wait..
Minima @ 16/02/2021 15:22:55 [56.2 MB] : Checking DB.. 100%
Minima @ 16/02/2021 15:22:56 [61.0 MB] : Network Startup..
Minima @ 16/02/2021 15:22:56 [61.1 MB] : Minima server started on 9001
Minima @ 16/02/2021 15:22:56 [61.6 MB] : RPC Server started on port : 9002
Minima @ 16/02/2021 15:22:56 [61.7 MB] : WebSocket Server started on port 9003
Minima @ 16/02/2021 15:22:56 [61.7 MB] : Attempting to connect to 35.204.62.177:9001
Minima @ 16/02/2021 15:22:56 [61.8 MB] : Service : Initial Sync listen for complete..
Minima @ 16/02/2021 15:22:56 [61.8 MB] : Service : Initialise end..
Minima @ 16/02/2021 15:22:57 [73.0 MB] : Greeting Message : 339.1 KB
Minima @ 16/02/2021 15:22:57 [75.4 MB] : DIFFERENT VERSION ON GREETING 0.97.10
Minima @ 16/02/2021 15:22:57 [75.4 MB] : ACTIVITY SYNC COMPLETE : [ CONSENSUS_NOTIFY_INITIALSYNC,  ]
Minima @ 16/02/2021 15:22:57 [75.4 MB] : Service : Install all DAPPS..
Minima @ 16/02/2021 15:22:57 [82.1 MB] : GREETING mytip:118461 mycascade:114141 greetingtip:118474 greetingcascade:114080
Minima @ 16/02/2021 15:22:57 [82.1 MB] : ACTIVITY : GET STARTED
Minima @ 16/02/2021 15:22:57 [82.5 MB] : Greeting Crossover block found : 118461
Minima @ 16/02/2021 15:22:58 [84.9 MB] : TxPoW List Message : 15.3 KB
Minima @ 16/02/2021 15:22:58 [48.9 MB] : INVALID BLOCK DIFFICULTY 118462
Minima @ 16/02/2021 15:22:58 [63.9 MB] : Recalculate MiniDAPPS @ 192.168.10.47
Minima @ 16/02/2021 15:22:58 [63.9 MB] : All database connections closed
Minima @ 16/02/2021 15:22:58 [64.6 MB] : ACTIVITY SYNC COMPLETE : [ CONSENSUS_NOTIFY_INITIALSYNC,  ]
Minima @ 16/02/2021 15:22:58 [64.6 MB] : Service : Install DAPPS - not first run..
Minima @ 16/02/2021 15:22:58 [64.7 MB] : ACTIVITY : GET STARTED
Minima @ 16/02/2021 15:22:58 [64.8 MB] : MiniDAPP server started on port 9004
Minima @ 16/02/2021 15:23:04 [57.0 MB] : Maxima Server started on port : 9005
Minima @ 16/02/2021 15:23:11 [114.0 MB] : NEW BALANCE : [{"tokenid":"0x00","token":"Minima","total":"1000000000","confirmed":"50","unconfirmed":"0","mempool":"0","sendable":"50"}]
Minima @ 16/02/2021 15:23:28 [118.7 MB] : Create SQL Connection to /data/user/0/global.org.minima/files/webroot/minidapps/0x8668421E432F6B5E66683BAF4C0C51AA9937B71B/_sqldb
Minima @ 16/02/2021 15:23:42 [37.4 MB] : START TXPOW MINING {"inputs":[{"coinid":"0xFEED50FEED50FEED50FEED50","address":"0x1F5215419EE7D3A2D2EAF4235E68F5072B0242E5","mxaddress":"MxD5JBKQM647J2FUXK6QRV42HVA4VQEQXF","amount":"50","tokenid":"0x00","floating":false}],"outputs":[{"coinid":"0x00","address":"0x39940875EE2FCF6974D85AC1044BD2CEC70E89D5","mxaddress":"MxHGKAQ5POF7HWS5GYLLAQIS6SZ3DQ5COV","amount":"25","tokenid":"0x00","floating":false},{"coinid":"0x00","address":"0xA04E4071E5C0BA60B13AD9D97902E77A89AAD012","mxaddress":"MxUBHEA4PFYC5GBMJ23HMXSAXHPKE2VUAS","amount":"25","tokenid":"0x00","floating":false}],"state":[],"linkhash":"0x00"}
Minima @ 16/02/2021 15:23:43 [59.8 MB] : TXPOW MINED!
Minima @ 16/02/2021 15:23:43 [60.2 MB] : NEW BALANCE : [{"tokenid":"0x00","token":"Minima","total":"1000000000","confirmed":"50","unconfirmed":"0","mempool":"50","sendable":"50"}]
Minima @ 16/02/2021 15:26:25 [37.7 MB] : START TXPOW MINING {"inputs":[{"coinid":"0xE23E0D0504897F386068A5901BAB45969D47FFB9C1F9876C2524535EFDAF743376317D4DB1FC816B759AE10358A42AB747338D0326CD35332A0E04F801E4DF71","address":"0x6FA6C3078B6F8CC59D88B8D47C661CD34E891707","mxaddress":"MxN6TMGB4LN6GMLHMIXDKHYZQ42NHISFYH","amount":"25","tokenid":"0x00","floating":false}],"outputs":[{"coinid":"0x00","address":"0x482F51D3E6E86822884E54B3DB7DC675698373E5","mxaddress":"MxJAXVDU7G5BUCFCCOKSZ5W7OGOVUYG47F","amount":"0.003658","tokenid":"0xFF","floating":false},{"coinid":"0x00","address":"0x4A75A29FAE3F5C0EED30B82070F9B49CB7B127D2","mxaddress":"MxJJ22FH5OH5OA53JQXAQHB6NUTS33CJ6S","amount":"24.996342","tokenid":"0x00","floating":false}],"state":[],"tokengen":{"tokenid":"0x76CE7F4DFB12763DE366C42C65A5DBDBD76B2D14AB6D1B0D34AD2E43606B3DAFA6F2ABE7CA02B64270BB6E6E2DF09E4FDF6766B765AF6DAD539C976B35F61D98","token":"M1","description":"","icon":"","proof":"","total":"3658","script":"ASSERT FLOOR ( @AMOUNT ) EQ @AMOUNT LET checkout = 0 WHILE ( checkout LT @TOTOUT ) DO IF GETOUTTOK ( checkout ) EQ @TOKENID THEN LET outamt = GETOUTAMT ( checkout ) ASSERT FLOOR ( outamt ) EQ outamt ENDIF LET checkout = INC ( checkout ) ENDWHILE RETURN TRUE","coinid":"0x00","totalamount":"0.003658","scale":"6","scalefactor":"1000000"},"linkhash":"0x00"}
Minima @ 16/02/2021 15:26:27 [60.2 MB] : NOTFINISHED 26593
Minima @ 16/02/2021 15:26:27 [65.4 MB] : START TXPOW MINING {"inputs":[{"coinid":"0xE23E0D0504897F386068A5901BAB45969D47FFB9C1F9876C2524535EFDAF743376317D4DB1FC816B759AE10358A42AB747338D0326CD35332A0E04F801E4DF71","address":"0x6FA6C3078B6F8CC59D88B8D47C661CD34E891707","mxaddress":"MxN6TMGB4LN6GMLHMIXDKHYZQ42NHISFYH","amount":"25","tokenid":"0x00","floating":false}],"outputs":[{"coinid":"0x00","address":"0x482F51D3E6E86822884E54B3DB7DC675698373E5","mxaddress":"MxJAXVDU7G5BUCFCCOKSZ5W7OGOVUYG47F","amount":"0.003658","tokenid":"0xFF","floating":false},{"coinid":"0x00","address":"0x4A75A29FAE3F5C0EED30B82070F9B49CB7B127D2","mxaddress":"MxJJ22FH5OH5OA53JQXAQHB6NUTS33CJ6S","amount":"24.996342","tokenid":"0x00","floating":false}],"state":[],"tokengen":{"tokenid":"0x76CE7F4DFB12763DE366C42C65A5DBDBD76B2D14AB6D1B0D34AD2E43606B3DAFA6F2ABE7CA02B64270BB6E6E2DF09E4FDF6766B765AF6DAD539C976B35F61D98","token":"M1","description":"","icon":"","proof":"","total":"3658","script":"ASSERT FLOOR ( @AMOUNT ) EQ @AMOUNT LET checkout = 0 WHILE ( checkout LT @TOTOUT ) DO IF GETOUTTOK ( checkout ) EQ @TOKENID THEN LET outamt = GETOUTAMT ( checkout ) ASSERT FLOOR ( outamt ) EQ outamt ENDIF LET checkout = INC ( checkout ) ENDWHILE RETURN TRUE","coinid":"0x00","totalamount":"0.003658","scale":"6","scalefactor":"1000000"},"linkhash":"0x00"}
Minima @ 16/02/2021 15:26:28 [62.9 MB] : TXPOW MINED!
Minima @ 16/02/2021 15:26:28 [65.6 MB] : NEW BALANCE : [{"tokenid":"0x00","token":"Minima","total":"1000000000","confirmed":"50","unconfirmed":"0","mempool":"49.996342","sendable":"25"}]
Minima @ 16/02/2021 15:30:52 [43.4 MB] : START TXPOW MINING {"inputs":[{"coinid":"0x2207D731C48BFE57464AA002CF4510D6770F0BEF65059CDDEAB21858AA7E424AD6827484EC9539AA5F379A7D5207E1DEB5D7E0E6FD1647201E7A68B25A7D7EAC","address":"0x71B1C27A439A65EB486EE8902570A2D67920D7A5","mxaddress":"MxOGY4E6SDTJS6WSDO5CICK4FC2Z4SBV5F","amount":"25","tokenid":"0x00","floating":false}],"outputs":[{"coinid":"0x00","address":"0x00","mxaddress":"0x00","amount":"1","tokenid":"0x00","floating":false},{"coinid":"0x00","address":"0x21985C6B31DC3735A9A5A129D44AE7C9CDE4D519","mxaddress":"MxEGMFY2ZR3Q3TLKNFUEU5ISXHZHG6JVIZ","amount":"24","tokenid":"0x00","floating":false}],"state":[],"linkhash":"0x00"}
Minima @ 16/02/2021 15:30:54 [65.9 MB] : NOTFINISHED 26659
Minima @ 16/02/2021 15:30:54 [72.5 MB] : START TXPOW MINING {"inputs":[{"coinid":"0x2207D731C48BFE57464AA002CF4510D6770F0BEF65059CDDEAB21858AA7E424AD6827484EC9539AA5F379A7D5207E1DEB5D7E0E6FD1647201E7A68B25A7D7EAC","address":"0x71B1C27A439A65EB486EE8902570A2D67920D7A5","mxaddress":"MxOGY4E6SDTJS6WSDO5CICK4FC2Z4SBV5F","amount":"25","tokenid":"0x00","floating":false}],"outputs":[{"coinid":"0x00","address":"0x00","mxaddress":"0x00","amount":"1","tokenid":"0x00","floating":false},{"coinid":"0x00","address":"0x21985C6B31DC3735A9A5A129D44AE7C9CDE4D519","mxaddress":"MxEGMFY2ZR3Q3TLKNFUEU5ISXHZHG6JVIZ","amount":"24","tokenid":"0x00","floating":false}],"state":[],"linkhash":"0x00"}
Minima @ 16/02/2021 15:30:56 [83.0 MB] : NOTFINISHED 27549
Minima @ 16/02/2021 15:30:57 [49.3 MB] : START TXPOW MINING {"inputs":[{"coinid":"0x2207D731C48BFE57464AA002CF4510D6770F0BEF65059CDDEAB21858AA7E424AD6827484EC9539AA5F379A7D5207E1DEB5D7E0E6FD1647201E7A68B25A7D7EAC","address":"0x71B1C27A439A65EB486EE8902570A2D67920D7A5","mxaddress":"MxOGY4E6SDTJS6WSDO5CICK4FC2Z4SBV5F","amount":"25","tokenid":"0x00","floating":false}],"outputs":[{"coinid":"0x00","address":"0x00","mxaddress":"0x00","amount":"1","tokenid":"0x00","floating":false},{"coinid":"0x00","address":"0x21985C6B31DC3735A9A5A129D44AE7C9CDE4D519","mxaddress":"MxEGMFY2ZR3Q3TLKNFUEU5ISXHZHG6JVIZ","amount":"24","tokenid":"0x00","floating":false}],"state":[],"linkhash":"0x00"}
Minima @ 16/02/2021 15:30:59 [62.7 MB] : NOTFINISHED 27373
Minima @ 16/02/2021 15:30:59 [69.3 MB] : START TXPOW MINING {"inputs":[{"coinid":"0x2207D731C48BFE57464AA002CF4510D6770F0BEF65059CDDEAB21858AA7E424AD6827484EC9539AA5F379A7D5207E1DEB5D7E0E6FD1647201E7A68B25A7D7EAC","address":"0x71B1C27A439A65EB486EE8902570A2D67920D7A5","mxaddress":"MxOGY4E6SDTJS6WSDO5CICK4FC2Z4SBV5F","amount":"25","tokenid":"0x00","floating":false}],"outputs":[{"coinid":"0x00","address":"0x00","mxaddress":"0x00","amount":"1","tokenid":"0x00","floating":false},{"coinid":"0x00","address":"0x21985C6B31DC3735A9A5A129D44AE7C9CDE4D519","mxaddress":"MxEGMFY2ZR3Q3TLKNFUEU5ISXHZHG6JVIZ","amount":"24","tokenid":"0x00","floating":false}],"state":[],"linkhash":"0x00"}
Minima @ 16/02/2021 15:31:01 [77.2 MB] : NOTFINISHED 27749
Minima @ 16/02/2021 15:31:02 [43.7 MB] : START TXPOW MINING {"inputs":[{"coinid":"0x2207D731C48BFE57464AA002CF4510D6770F0BEF65059CDDEAB21858AA7E424AD6827484EC9539AA5F379A7D5207E1DEB5D7E0E6FD1647201E7A68B25A7D7EAC","address":"0x71B1C27A439A65EB486EE8902570A2D67920D7A5","mxaddress":"MxOGY4E6SDTJS6WSDO5CICK4FC2Z4SBV5F","amount":"25","tokenid":"0x00","floating":false}],"outputs":[{"coinid":"0x00","address":"0x00","mxaddress":"0x00","amount":"1","tokenid":"0x00","floating":false},{"coinid":"0x00","address":"0x21985C6B31DC3735A9A5A129D44AE7C9CDE4D519","mxaddress":"MxEGMFY2ZR3Q3TLKNFUEU5ISXHZHG6JVIZ","amount":"24","tokenid":"0x00","floating":false}],"state":[],"linkhash":"0x00"}
Minima @ 16/02/2021 15:31:04 [71.6 MB] : NOTFINISHED 27222
Minima @ 16/02/2021 15:31:04 [78.2 MB] : START TXPOW MINING {"inputs":[{"coinid":"0x2207D731C48BFE57464AA002CF4510D6770F0BEF65059CDDEAB21858AA7E424AD6827484EC9539AA5F379A7D5207E1DEB5D7E0E6FD1647201E7A68B25A7D7EAC","address":"0x71B1C27A439A65EB486EE8902570A2D67920D7A5","mxaddress":"MxOGY4E6SDTJS6WSDO5CICK4FC2Z4SBV5F","amount":"25","tokenid":"0x00","floating":false}],"outputs":[{"coinid":"0x00","address":"0x00","mxaddress":"0x00","amount":"1","tokenid":"0x00","floating":false},{"coinid":"0x00","address":"0x21985C6B31DC3735A9A5A129D44AE7C9CDE4D519","mxaddress":"MxEGMFY2ZR3Q3TLKNFUEU5ISXHZHG6JVIZ","amount":"24","tokenid":"0x00","floating":false}],"state":[],"linkhash":"0x00"}
Minima @ 16/02/2021 15:31:05 [57.3 MB] : TXPOW MINED!
Minima @ 16/02/2021 15:31:05 [59.7 MB] : NEW BALANCE : [{"tokenid":"0x00","token":"Minima","total":"1000000000","confirmed":"50","unconfirmed":"0","mempool":"48.996342","sendable":"0"}]
Minima @ 16/02/2021 15:33:47 [48.5 MB] : START TXPOW MINING {"inputs":[{"coinid":"0xFEED50FEED50FEED50FEED50","address":"0x1F5215419EE7D3A2D2EAF4235E68F5072B0242E5","mxaddress":"MxD5JBKQM647J2FUXK6QRV42HVA4VQEQXF","amount":"50","tokenid":"0x00","floating":false}],"outputs":[{"coinid":"0x00","address":"0xE45C8DB6F4EFCB87193283A86920E69A65E6D1F7","mxaddress":"Mx4ROI3NXU57FYOGJSQOUGSIHGTJS6NUPX","amount":"25","tokenid":"0x00","floating":false},{"coinid":"0x00","address":"0xE2E3B92E255556BFBC507DD1E53A1781D4DA3E6B","mxaddress":"Mx4LR3SLRFKVLL7PCQPXI6KOQXQHKNUPTL","amount":"25","tokenid":"0x00","floating":false}],"state":[],"linkhash":"0x00"}
Minima @ 16/02/2021 15:33:49 [78.6 MB] : NOTFINISHED 27383
Minima @ 16/02/2021 15:33:49 [82.9 MB] : START TXPOW MINING {"inputs":[{"coinid":"0xFEED50FEED50FEED50FEED50","address":"0x1F5215419EE7D3A2D2EAF4235E68F5072B0242E5","mxaddress":"MxD5JBKQM647J2FUXK6QRV42HVA4VQEQXF","amount":"50","tokenid":"0x00","floating":false}],"outputs":[{"coinid":"0x00","address":"0xE45C8DB6F4EFCB87193283A86920E69A65E6D1F7","mxaddress":"Mx4ROI3NXU57FYOGJSQOUGSIHGTJS6NUPX","amount":"25","tokenid":"0x00","floating":false},{"coinid":"0x00","address":"0xE2E3B92E255556BFBC507DD1E53A1781D4DA3E6B","mxaddress":"Mx4LR3SLRFKVLL7PCQPXI6KOQXQHKNUPTL","amount":"25","tokenid":"0x00","floating":false}],"state":[],"linkhash":"0x00"}
Minima @ 16/02/2021 15:33:51 [53.4 MB] : NOTFINISHED 27439
Minima @ 16/02/2021 15:33:51 [57.7 MB] : START TXPOW MINING {"inputs":[{"coinid":"0xFEED50FEED50FEED50FEED50","address":"0x1F5215419EE7D3A2D2EAF4235E68F5072B0242E5","mxaddress":"MxD5JBKQM647J2FUXK6QRV42HVA4VQEQXF","amount":"50","tokenid":"0x00","floating":false}],"outputs":[{"coinid":"0x00","address":"0xE45C8DB6F4EFCB87193283A86920E69A65E6D1F7","mxaddress":"Mx4ROI3NXU57FYOGJSQOUGSIHGTJS6NUPX","amount":"25","tokenid":"0x00","floating":false},{"coinid":"0x00","address":"0xE2E3B92E255556BFBC507DD1E53A1781D4DA3E6B","mxaddress":"Mx4LR3SLRFKVLL7PCQPXI6KOQXQHKNUPTL","amount":"25","tokenid":"0x00","floating":false}],"state":[],"linkhash":"0x00"}
Minima @ 16/02/2021 15:33:53 [63.6 MB] : NOTFINISHED 27254
Minima @ 16/02/2021 15:33:53 [67.9 MB] : START TXPOW MINING {"inputs":[{"coinid":"0xFEED50FEED50FEED50FEED50","address":"0x1F5215419EE7D3A2D2EAF4235E68F5072B0242E5","mxaddress":"MxD5JBKQM647J2FUXK6QRV42HVA4VQEQXF","amount":"50","tokenid":"0x00","floating":false}],"outputs":[{"coinid":"0x00","address":"0xE45C8DB6F4EFCB87193283A86920E69A65E6D1F7","mxaddress":"Mx4ROI3NXU57FYOGJSQOUGSIHGTJS6NUPX","amount":"25","tokenid":"0x00","floating":false},{"coinid":"0x00","address":"0xE2E3B92E255556BFBC507DD1E53A1781D4DA3E6B","mxaddress":"Mx4LR3SLRFKVLL7PCQPXI6KOQXQHKNUPTL","amount":"25","tokenid":"0x00","floating":false}],"state":[],"linkhash":"0x00"}
Minima @ 16/02/2021 15:33:53 [68.8 MB] : TXPOW MINED!
Minima @ 16/02/2021 15:33:53 [69.2 MB] : NEW BALANCE : [{"tokenid":"0x00","token":"Minima","total":"1000000000","confirmed":"50","unconfirmed":"0","mempool":"98.996342","sendable":"0"}]`

**Comment by eurobuddha** [comment]
fixed in 97.13
